# -*- coding: utf-8 -*-
"""
Lauree del catalogo che non avevano ancora una pagina dedicata (aggiunte il 10 ottobre 2026).
Le 6 lauree "storiche" (Giurisprudenza, Economia Aziendale, Scienze Psicologiche L-24,
Scienze dell'Educazione L-19, Ingegneria Informatica L-8, Scienze Motorie L-22) restano in pagine.py.

Ogni voce ha una parola chiave principale DIVERSA dalle altre (anti-cannibalizzazione):
triennale e magistrale della stessa area si distinguono sempre per "magistrale" + classe.
Il titolo e' rilasciato dall'ateneo convenzionato: qui non si nomina.
"""

# area -> (icona, sfondo della card)
AREE = {
    "eco": ("&#128200;", "bg-economia", "Economia e turismo"),
    "giu": ("&#9878;", "bg-giuris", "Giuridico e sociale"),
    "ing": ("&#9881;", "bg-informatica", "Ingegneria"),
    "let": ("&#128214;", "bg-educazione", "Lettere, arti e lingue"),
    "ped": ("&#127891;", "bg-educazione", "Pedagogia"),
    "psi": ("&#129504;", "bg-psico", "Psicologia"),
    "bio": ("&#129516;", "bg-certif", "Biologia e nutrizione"),
    "mot": ("&#127939;", "bg-motorie", "Scienze motorie"),
}

LAUREE = {
    # ------------------------------------------------------------------ ECONOMIA E TURISMO
    "l15": dict(
        code="L-15", typ="t", area="eco", years=3, cfu=180,
        url="/corsi-di-laurea/scienze-turismo/",
        name="Scienze del Turismo per il management e i beni culturali", short="Scienze del Turismo L-15",
        title="Laurea online in Scienze del Turismo (L-15) | UNICESD Olympo",
        desc="Laurea triennale online in Scienze del Turismo L-15: management dell'ospitalità, turismo culturale e beni culturali. 180 CFU, esami in sede, tutor dedicato.",
        h1="Laurea in Scienze del Turismo online <span class=\"grad\">L-15</span>",
        lead="Il triennio per chi vuole lavorare nell'ospitalità, nella promozione dei territori e nella valorizzazione del patrimonio culturale: lezioni online sempre disponibili, esami in sede e un tutor UNICESD Olympo dall'iscrizione alla laurea.",
        intro=[
            "Il turismo è uno dei motori dell'economia italiana e, in Sicilia, una delle prime fonti di lavoro. Il corso in <b>Scienze del Turismo per il management e i beni culturali</b> (classe <b>L-15</b>) unisce le competenze economico-gestionali che servono per guidare un'impresa turistica a quelle storico-artistiche necessarie per raccontare e promuovere un territorio.",
            "È pensato per chi lavora già nel settore (strutture ricettive, agenzie di viaggio, guide, uffici turistici) e vuole un titolo universitario, ma anche per chi parte da zero e vuole costruirsi una professione in un mercato sempre più internazionale e digitale.",
        ],
        materie=["Economia e gestione delle imprese turistiche", "Marketing turistico e digitale", "Geografia del turismo", "Diritto del turismo e dei beni culturali", "Storia dell'arte e del patrimonio", "Lingue straniere per il turismo", "Statistica per il turismo", "Organizzazione di eventi e destination management"],
        indirizzi=[
            ("Management e turismo culturale", "Per chi vuole progettare itinerari, musei diffusi, festival ed esperienze culturali, e gestire i flussi di visitatori."),
            ("Management dell'ospitalità e del territorio", "Per chi lavora o vuole lavorare in hotel, resort, strutture extralberghiere e consorzi turistici: revenue, qualità del servizio, promozione territoriale."),
            ("Global tourism and cultural heritage management", "Indirizzo in lingua inglese, orientato ai mercati internazionali e alla gestione del patrimonio in chiave globale."),
        ],
        sbocchi=["Responsabile di struttura ricettiva o di reparto (front office, booking, revenue)", "Destination manager e operatore di consorzi e DMO", "Progettista di itinerari ed esperienze turistiche", "Addetto alla promozione in enti pubblici, musei e fondazioni", "Organizzatore di eventi, congressi e incentive", "Imprenditore nel turismo esperienziale ed enogastronomico"],
        accesso="Serve il diploma di scuola secondaria superiore (quinquennale) o un titolo estero riconosciuto. Non c'è test d'ingresso a numero chiuso: l'ateneo prevede una verifica delle conoscenze iniziali che non impedisce l'iscrizione.",
        dopo="Con la laurea L-15 si può proseguire con una laurea magistrale di area turistica o economica, oppure specializzarsi con il nostro <a href=\"/master-universitari/management-imprese-turistiche/\">Master in Management delle Imprese Turistiche</a>.",
        faq=[
            ("Posso farmi riconoscere l'esperienza nel turismo?", "Sì, l'esperienza lavorativa documentata e i corsi già frequentati possono valere crediti. La valutazione preliminare è gratuita e la delibera definitiva spetta all'ateneo."),
            ("Le lingue straniere sono obbligatorie?", "Il piano di studi prevede insegnamenti di lingua straniera, come tutte le lauree in turismo. Se scegli l'indirizzo internazionale, buona parte della didattica è in inglese."),
            ("Che differenza c'è con il Master in Management Turistico?", "La laurea L-15 è il titolo di base, per chi ha il diploma. Il master è una specializzazione post laurea di un anno, per chi è già laureato."),
        ],
        related=["lm56", "c2", "m2"],
    ),
    "lm56": dict(
        code="LM-56", typ="m", area="eco", years=2, cfu=120,
        url="/corsi-di-laurea/magistrale-scienze-economia/",
        name="Scienze dell'Economia (magistrale)", short="Magistrale Scienze dell'Economia LM-56",
        title="Laurea magistrale online in Scienze dell'Economia LM-56 | UNICESD",
        desc="Laurea magistrale online in Scienze dell'Economia LM-56: scienze economiche, green economy, e-commerce e digital management. 120 CFU, esami in sede.",
        h1="Laurea magistrale in Scienze dell'Economia <span class=\"grad\">LM-56</span>",
        lead="Due anni per passare dalle basi dell'economia alla capacità di leggere mercati, politiche pubbliche e trasformazione digitale delle imprese. Online, con esami in sede e un tutor dedicato.",
        intro=[
            "La magistrale in <b>Scienze dell'Economia</b> (classe <b>LM-56</b>) è il passo successivo per chi ha una laurea triennale di area economica e vuole ruoli di analisi, consulenza e direzione. Il corso approfondisce macroeconomia, economia pubblica, finanza ed econometria, e li applica alle due grandi transizioni in corso: quella ecologica e quella digitale.",
            "La classe LM-56 è anche tra quelle che consentono di accedere, dopo il tirocinio, all'esame di Stato per la sezione A dell'Albo dei Dottori Commercialisti ed Esperti Contabili, secondo la normativa vigente.",
        ],
        materie=["Macroeconomia e politica economica", "Economia pubblica e dei mercati", "Econometria e analisi dei dati", "Finanza e mercati finanziari", "Economia dell'ambiente e dell'energia", "Economia digitale e piattaforme", "Diritto dell'economia", "Strategia d'impresa"],
        indirizzi=[
            ("Scienze economiche", "Il percorso generalista: analisi economica, politiche pubbliche, finanza. Adatto a chi punta a uffici studi, banche, consulenza e concorsi."),
            ("Green economy e sostenibilità", "Economia circolare, energia, rendicontazione ESG e finanza sostenibile: le competenze che le imprese devono avere per i nuovi obblighi europei."),
            ("e-Commerce e digital management", "Modelli di business digitali, marketplace, analisi dei dati di vendita e gestione dei canali online."),
        ],
        sbocchi=["Economista e analista in uffici studi, banche e assicurazioni", "Consulente aziendale e di direzione", "Sustainability manager ed ESG analyst", "E-commerce manager e digital business analyst", "Funzionario nella pubblica amministrazione e nelle autorità di regolazione", "Accesso all'esame di Stato per Dottore Commercialista (sez. A), previo tirocinio"],
        accesso="Serve una laurea triennale (o titolo equipollente) con i requisiti curricolari previsti dall'ateneo, di norma un numero minimo di crediti nei settori economici, aziendali, statistico-matematici e giuridici. Se ne mancano alcuni, si possono recuperare con i <a href=\"/corsi-singoli-cfu/\">corsi singoli</a> prima dell'iscrizione.",
        dopo="Dopo la magistrale si può accedere a master di II livello, dottorati di ricerca e, con il tirocinio, all'esame di Stato per la professione di commercialista.",
        faq=[
            ("Ho una laurea triennale non economica: posso iscrivermi?", "Dipende dai crediti che hai già nei settori richiesti. Ti facciamo una verifica gratuita del piano di studi: se mancano pochi CFU li recuperi con i corsi singoli."),
            ("Con la LM-56 posso diventare commercialista?", "La classe LM-56 è tra quelle ammesse all'esame di Stato per la sezione A dell'Albo, dopo il tirocinio previsto dalla legge. Ti aiutiamo a capire i passaggi nel tuo caso."),
            ("Qual è l'indirizzo più richiesto dalle aziende?", "Oggi le competenze su sostenibilità ed ESG e quelle sul digitale sono le più cercate; l'indirizzo generalista resta il più adatto per concorsi e uffici studi."),
        ],
        related=["c2", "l15", "m5"],
    ),
    # ------------------------------------------------------------------ GIURIDICO E SOCIALE
    "l14": dict(
        code="L-14", typ="t", area="giu", years=3, cfu=180,
        url="/corsi-di-laurea/servizi-giuridici/",
        name="Servizi giuridici", short="Servizi Giuridici L-14",
        title="Laurea online in Servizi Giuridici L-14 e Criminologia",
        desc="Laurea triennale online in Servizi Giuridici L-14 con indirizzi in criminologia, scienze penitenziarie, consulente del lavoro e amministratore di condominio.",
        h1="Laurea in Servizi Giuridici online <span class=\"grad\">L-14</span>",
        lead="Tre anni di diritto applicato, con cinque indirizzi che portano dritti a una professione: dall'impresa al carcere, dalla consulenza del lavoro alla gestione dei condomini.",
        intro=[
            "La laurea in <b>Servizi giuridici</b> (classe <b>L-14</b>) è la triennale di area giuridica: meno teorica della magistrale a ciclo unico in Giurisprudenza, molto più vicina al lavoro quotidiano di uffici legali, aziende, enti pubblici e studi professionali.",
            "Ha senso per chi lavora già (forze dell'ordine, polizia penitenziaria, impiegati amministrativi, operatori di studi professionali) e vuole un titolo che valorizzi l'esperienza, e per chi cerca una laurea di tre anni spendibile nei concorsi pubblici. Gli esami già sostenuti possono essere riconosciuti anche in un eventuale passaggio a <a href=\"/corsi-di-laurea/giurisprudenza/\">Giurisprudenza</a>.",
        ],
        materie=["Istituzioni di diritto privato e pubblico", "Diritto costituzionale e amministrativo", "Diritto penale e procedura penale", "Diritto del lavoro e della previdenza", "Diritto commerciale e tributario", "Criminologia e sociologia della devianza", "Diritto dell'Unione europea", "Informatica giuridica"],
        indirizzi=[
            ("Servizi giuridici per l'impresa", "Contratti, societario, fisco e compliance per gli uffici legali e amministrativi delle aziende."),
            ("Scienze penitenziarie", "Ordinamento penitenziario, esecuzione della pena, trattamento e reinserimento: per chi lavora o vuole lavorare negli istituti di pena."),
            ("Criminologia", "Le cause del crimine, la vittimologia, le tecniche investigative e la prevenzione, con una solida base giuridica."),
            ("Consulente del lavoro e giurista d'impresa", "Diritto del lavoro, previdenza, buste paga e relazioni sindacali: la base per il praticantato da consulente del lavoro."),
            ("Amministratori di condominio", "Diritto condominiale, contabilità, sicurezza degli edifici e gestione dei conflitti per chi amministra o vuole amministrare immobili."),
        ],
        sbocchi=["Consulente del lavoro (dopo praticantato ed esame di Stato)", "Giurista d'impresa e addetto agli uffici legali e del personale", "Operatore nel sistema penitenziario e nei servizi per l'esecuzione penale", "Analista e consulente in ambito criminologico e della sicurezza", "Amministratore di condominio e property manager", "Funzionario nei concorsi pubblici che richiedono la laurea triennale"],
        accesso="Serve il diploma di scuola secondaria superiore. Non c'è numero chiuso. Per chi viene dalle forze dell'ordine o da altri corsi universitari è prevista la valutazione dei crediti già maturati.",
        dopo="Dopo la L-14 si può proseguire verso la magistrale a ciclo unico in Giurisprudenza (con il riconoscimento degli esami compatibili), verso master giuridici o, per la consulenza del lavoro, verso il praticantato e l'esame di Stato.",
        faq=[
            ("Con la L-14 posso fare l'avvocato?", "No: per l'avvocatura, la magistratura e il notariato serve la laurea magistrale a ciclo unico in Giurisprudenza (LMG-01). La L-14 è il percorso giusto per le altre professioni giuridiche."),
            ("Sono nelle forze dell'ordine: mi riconoscono i corsi?", "Molto spesso sì, una parte della formazione professionale può valere crediti. Mandaci il tuo stato di servizio e i titoli: la valutazione è gratuita."),
            ("Che cosa cambia tra criminologia e scienze penitenziarie?", "Criminologia studia il fenomeno criminale e la sua prevenzione; scienze penitenziarie si concentra su quello che succede dopo la condanna: esecuzione della pena, trattamento e reinserimento."),
        ],
        related=["c1", "l36", "lm51"],
    ),
    "l36": dict(
        code="L-36", typ="t", area="giu", years=3, cfu=180,
        url="/corsi-di-laurea/scienze-politiche/",
        name="Scienze politiche e sociali", short="Scienze Politiche L-36",
        title="Laurea online in Scienze Politiche (L-36) | UNICESD Olympo",
        desc="Laurea triennale online in Scienze Politiche e Sociali L-36: istituzioni, economia e pubblica amministrazione. 180 CFU, ideale per concorsi e carriere nella PA.",
        h1="Laurea in Scienze Politiche online <span class=\"grad\">L-36</span>",
        lead="La laurea che spiega come funzionano istituzioni, società ed economia, e che apre le porte dei concorsi pubblici. Online, con esami in sede e un tutor sempre raggiungibile.",
        intro=[
            "<b>Scienze politiche e sociali</b> (classe <b>L-36</b>) è uno dei corsi più versatili: diritto, economia, storia, sociologia e relazioni internazionali in un unico percorso. È la laurea tradizionalmente scelta da chi punta alla pubblica amministrazione, perché copre molte delle materie richieste nei concorsi.",
            "Molti dei nostri iscritti sono dipendenti pubblici, militari e operatori del terzo settore che vogliono crescere di livello o cambiare ruolo: la didattica asincrona permette di studiare senza lasciare il lavoro.",
        ],
        materie=["Scienza politica", "Diritto pubblico e costituzionale", "Diritto amministrativo", "Economia politica", "Storia contemporanea", "Sociologia", "Relazioni internazionali", "Statistica sociale"],
        indirizzi=[
            ("Politica, società e istituzioni", "Il percorso più ampio: istituzioni italiane ed europee, partiti, movimenti, comunicazione politica e processi sociali."),
            ("Politica, economia e Pubblica Amministrazione", "Pensato per chi lavora o vuole lavorare nella PA: organizzazione degli enti, bilancio pubblico, appalti e management pubblico."),
        ],
        sbocchi=["Funzionario e istruttore nella pubblica amministrazione", "Addetto agli affari istituzionali e alle relazioni esterne", "Operatore di organizzazioni internazionali e ONG", "Analista politico e sociale, ricercatore in istituti di sondaggio", "Collaboratore di partiti, sindacati e associazioni di categoria", "Responsabile di progetti finanziati (fondi europei e PNRR)"],
        accesso="Serve il diploma di scuola secondaria superiore. Non è previsto il numero chiuso. Per i dipendenti pubblici sono spesso attive convenzioni e agevolazioni: chiedici quale si applica al tuo ente.",
        dopo="Si può proseguire con le lauree magistrali di area politologica, economica o delle relazioni internazionali, oppure con master in management pubblico e in progettazione europea.",
        faq=[
            ("Scienze politiche serve per i concorsi?", "È una delle lauree più adatte: molti bandi per funzionari amministrativi chiedono una laurea in area giuridico-economico-politica e le materie d'esame coincidono in buona parte con il piano di studi."),
            ("Sono un dipendente pubblico: ci sono agevolazioni?", "Spesso sì, tra convenzioni con le amministrazioni e iniziative per la formazione del personale pubblico. Al colloquio verifichiamo cosa vale nel tuo caso."),
            ("Posso passare poi a Giurisprudenza?", "Sì, gli esami giuridici comuni vengono valutati per il riconoscimento nel corso a ciclo unico."),
        ],
        related=["l14", "l20", "c1"],
    ),
    "l20": dict(
        code="L-20", typ="t", area="giu", years=3, cfu=180,
        url="/corsi-di-laurea/scienze-comunicazione/",
        name="Scienze della comunicazione", short="Scienze della Comunicazione L-20",
        title="Laurea online in Scienze della Comunicazione (L-20) | UNICESD",
        desc="Laurea triennale online in Scienze della Comunicazione L-20: digital marketing, comunicazione d'impresa, gaming e influencer. 180 CFU, esami in sede.",
        h1="Laurea in Scienze della Comunicazione online <span class=\"grad\">L-20</span>",
        lead="Comunicazione d'impresa e istituzionale, digital marketing, social e intrattenimento digitale: il triennio per lavorare dove oggi si costruiscono marchi e reputazioni.",
        intro=[
            "Il corso in <b>Scienze della comunicazione</b> (classe <b>L-20</b>) forma professionisti capaci di progettare messaggi, campagne e contenuti per aziende, enti e media. Accanto alle basi teoriche (semiotica, sociologia dei media, psicologia della comunicazione) ci sono materie molto concrete: scrittura per il web, analisi dei dati social, marketing digitale.",
            "Quattro indirizzi permettono di scegliere tra comunicazione tradizionale e nuove professioni, come la gestione dei creator e l'industria dei videogiochi.",
        ],
        materie=["Teorie e tecniche della comunicazione", "Sociologia dei media", "Semiotica", "Marketing e comunicazione d'impresa", "Scrittura per i media e per il web", "Diritto dell'informazione e della comunicazione", "Web analytics e social media", "Psicologia della comunicazione"],
        indirizzi=[
            ("Comunicazione istituzionale e d'impresa", "Uffici stampa, relazioni pubbliche, comunicazione interna e di crisi per aziende ed enti pubblici."),
            ("Digital marketing", "SEO, advertising, social media, e-mail marketing e misurazione dei risultati."),
            ("Digital entertainment and gaming", "L'industria dei videogiochi, degli esports e dell'intrattenimento digitale: produzione, community e modelli di business."),
            ("Influencer", "Personal branding, creazione di contenuti, rapporti con i brand e aspetti legali del lavoro da creator."),
        ],
        sbocchi=["Social media manager e content creator", "Addetto stampa e alle relazioni pubbliche", "Digital marketing specialist", "Copywriter e web editor", "Community manager per brand, gaming ed esports", "Addetto alla comunicazione di enti pubblici (legge 150/2000)"],
        accesso="Serve il diploma di scuola secondaria superiore. Non ci sono test selettivi.",
        dopo="Si può proseguire con le magistrali in comunicazione, marketing o giornalismo, oppure entrare subito nel mercato con un portfolio costruito durante i tre anni.",
        faq=[
            ("L'indirizzo Influencer è una laurea vera?", "Sì: è un indirizzo di una laurea triennale L-20, con lo stesso valore legale degli altri. Cambiano alcuni insegnamenti, centrati su personal branding e contenuti digitali."),
            ("Serve saper usare programmi di grafica?", "Non per iscriversi. Gli strumenti si imparano durante il corso; chi li conosce già parte avvantaggiato nei laboratori."),
            ("Posso lavorare in un ufficio stampa pubblico?", "La laurea in Scienze della comunicazione è tra i titoli richiesti per gli uffici stampa e comunicazione della pubblica amministrazione."),
        ],
        related=["l36", "l3", "lm56"],
    ),
    # ------------------------------------------------------------------ INGEGNERIA
    "l9": dict(
        code="L-9", typ="t", area="ing", years=3, cfu=180,
        url="/corsi-di-laurea/ingegneria-industriale/",
        name="Ingegneria industriale", short="Ingegneria Industriale L-9",
        title="Laurea online in Ingegneria Industriale (L-9) | UNICESD Olympo",
        desc="Laurea triennale online in Ingegneria Industriale L-9: indirizzi gestionale, energetico, chimico e veicoli ibridi ed elettrici. 180 CFU, esami in sede.",
        h1="Laurea in Ingegneria Industriale online <span class=\"grad\">L-9</span>",
        lead="La triennale per chi vuole progettare, produrre e gestire: impianti, energia, processi e la nuova mobilità elettrica. Studi online, sostieni gli esami in sede e hai un tutor che ti segue.",
        intro=[
            "<b>Ingegneria industriale</b> (classe <b>L-9</b>) è la laurea che dà le basi comuni a meccanica, energetica, chimica e gestionale: matematica, fisica, materiali, termodinamica, elettrotecnica. Su queste basi si innestano cinque indirizzi, tra cui uno dedicato alla mobilità ibrida ed elettrica.",
            "È molto scelta da periti industriali e tecnici che lavorano in azienda e vogliono il titolo da ingegnere: la didattica online permette di conciliare lo studio con i turni.",
        ],
        materie=["Analisi matematica e geometria", "Fisica generale", "Chimica", "Scienza e tecnologia dei materiali", "Fisica tecnica e termodinamica", "Elettrotecnica", "Meccanica applicata alle macchine", "Impianti industriali"],
        indirizzi=[
            ("Chimico", "Processi chimici industriali, impianti, sicurezza e ambiente."),
            ("Gestionale", "Organizzazione della produzione, logistica, qualità, economia e gestione d'impresa."),
            ("Energetico", "Produzione e uso efficiente dell'energia, fonti rinnovabili, impianti termici ed elettrici."),
            ("Veicoli ibridi ed elettrici", "Propulsione elettrica, batterie, sistemi di ricarica e progettazione dei veicoli di nuova generazione."),
            ("Energy engineering", "Indirizzo in lingua inglese sull'ingegneria dell'energia, per chi guarda a un contesto internazionale."),
        ],
        sbocchi=["Ingegnere iunior (Albo sez. B, dopo l'esame di Stato)", "Tecnico di produzione e responsabile di impianto", "Energy manager e progettista di impianti da fonti rinnovabili", "Addetto alla qualità, logistica e supply chain", "Tecnico nel settore automotive ed e-mobility", "Consulente per sicurezza ed efficienza energetica"],
        accesso="Serve il diploma di scuola secondaria superiore. È prevista una verifica delle conoscenze iniziali di matematica e fisica: chi ha lacune le colma con attività di recupero nel primo anno, senza perdere l'iscrizione.",
        dopo="La prosecuzione naturale è la <a href=\"/corsi-di-laurea/magistrale-ingegneria-industriale/\">laurea magistrale in Ingegneria industriale LM-33</a>, che dà accesso all'esame di Stato per la sezione A dell'Albo degli Ingegneri.",
        faq=[
            ("Sono perito industriale: ho un vantaggio?", "Sì, sulle materie tecniche partirai con più basi e, se hai già esami universitari o titoli post diploma, possiamo valutarne il riconoscimento."),
            ("Come si fanno i laboratori online?", "Gran parte delle esercitazioni si svolge con simulazioni e software; le prove d'esame si sostengono in sede, come previsto dall'ateneo."),
            ("Con la triennale posso firmare progetti?", "Con l'iscrizione alla sezione B dell'Albo (ingegnere iunior) puoi svolgere le attività previste dalla legge per quella sezione. Per le competenze piene serve la magistrale e la sezione A."),
        ],
        related=["lm33", "l7", "c5"],
    ),
    "l7": dict(
        code="L-7", typ="t", area="ing", years=3, cfu=180,
        url="/corsi-di-laurea/ingegneria-civile-ambientale/",
        name="Ingegneria civile e ambientale", short="Ingegneria Civile e Ambientale L-7",
        title="Laurea online in Ingegneria Civile e Ambientale (L-7) | UNICESD",
        desc="Laurea triennale online in Ingegneria Civile e Ambientale L-7: strutture, territorio, ambiente e paesaggio. 180 CFU, esami in sede, valutazione CFU gratuita.",
        h1="Laurea in Ingegneria Civile e Ambientale online <span class=\"grad\">L-7</span>",
        lead="Costruzioni, infrastrutture, territorio e ambiente: la triennale per geometri, tecnici di cantiere e per chiunque voglia diventare ingegnere studiando online.",
        intro=[
            "Il corso in <b>Ingegneria civile e ambientale</b> (classe <b>L-7</b>) insegna a progettare e gestire edifici, strade, opere idrauliche e interventi sul territorio, con un'attenzione crescente a sostenibilità, rischio sismico e idrogeologico e tutela del paesaggio.",
            "Molti iscritti sono geometri e tecnici già al lavoro in studi e imprese edili: con la laurea possono iscriversi all'Albo degli Ingegneri (sezione B) e ampliare le loro competenze professionali.",
        ],
        materie=["Analisi matematica e geometria", "Fisica", "Disegno e rappresentazione", "Scienza delle costruzioni", "Geotecnica", "Idraulica", "Topografia", "Ingegneria sanitaria-ambientale"],
        indirizzi=[
            ("Civile e ambientale", "Il percorso classico: strutture, infrastrutture, idraulica e ambiente."),
            ("Paesaggistico", "Pianificazione e progettazione nel rispetto del paesaggio, recupero del territorio, verde e infrastrutture ecologiche."),
        ],
        sbocchi=["Ingegnere iunior civile e ambientale (Albo sez. B)", "Tecnico di cantiere e direttore operativo", "Progettista nelle imprese di costruzione e negli studi tecnici", "Tecnico negli uffici tecnici comunali e regionali", "Consulente per la valutazione ambientale e la sicurezza", "Operatore nella pianificazione territoriale e paesaggistica"],
        accesso="Serve il diploma di scuola secondaria superiore. La verifica iniziale di matematica non è selettiva. Per i geometri può essere valutato il riconoscimento di attività formative pregresse.",
        dopo="La prosecuzione naturale è la <a href=\"/corsi-di-laurea/magistrale-ingegneria-civile/\">laurea magistrale in Ingegneria civile LM-23</a>, con accesso alla sezione A dell'Albo.",
        faq=[
            ("Sono geometra: perché laurearmi in ingegneria?", "Per accedere all'Albo degli Ingegneri e alle competenze che la legge riserva agli ingegneri, oltre che ai concorsi per uffici tecnici che chiedono la laurea."),
            ("Ci sono esami pratici?", "Le esercitazioni di progetto si svolgono con software e con il supporto dei docenti; le prove d'esame sono in sede."),
            ("Che cos'è l'indirizzo paesaggistico?", "Un percorso che unisce ingegneria e tutela del paesaggio: recupero del territorio, verde urbano, infrastrutture a basso impatto."),
        ],
        related=["lm23", "l9", "c5"],
    ),
    "lm33": dict(
        code="LM-33", typ="m", area="ing", years=2, cfu=120,
        url="/corsi-di-laurea/magistrale-ingegneria-industriale/",
        name="Ingegneria industriale (magistrale)", short="Magistrale Ingegneria Industriale LM-33",
        title="Magistrale online in Ingegneria Industriale LM-33 | UNICESD",
        desc="Laurea magistrale online in Ingegneria Industriale (meccanica) LM-33: termomeccanico, gestionale, progettuale e Industria 4.0. 120 CFU, esami in sede.",
        h1="Laurea magistrale in Ingegneria Industriale <span class=\"grad\">LM-33</span>",
        lead="Due anni per specializzarsi in progettazione meccanica, energia, gestione della produzione e fabbrica digitale. Per laureati triennali che lavorano e vogliono la sezione A dell'Albo.",
        intro=[
            "La magistrale in <b>Ingegneria industriale</b> (classe <b>LM-33</b>, ingegneria meccanica) porta al livello di progettazione e direzione: calcolo e progetto di macchine, sistemi energetici, organizzazione degli impianti e automazione della produzione.",
            "Con la laurea magistrale si accede all'esame di Stato per la <b>sezione A dell'Albo degli Ingegneri</b>, settore industriale, e ai ruoli di responsabilità tecnica nelle aziende.",
        ],
        materie=["Progettazione meccanica avanzata", "Macchine e sistemi energetici", "Impianti industriali", "Tecnologie di produzione", "Controlli automatici e meccatronica", "Gestione dei progetti e della manutenzione", "Metodi numerici per l'ingegneria", "Sistemi per l'Industria 4.0"],
        indirizzi=[
            ("Termomeccanico", "Macchine, motori, impianti termici e sistemi energetici."),
            ("Tecnologico gestionale", "Produzione, qualità, manutenzione e gestione degli impianti."),
            ("Progettuale meccanico", "Calcolo strutturale, CAD/CAE e progettazione di componenti e sistemi meccanici."),
            ("Industria 4.0", "Automazione, sensori, IoT industriale, digital twin e fabbrica connessa."),
        ],
        sbocchi=["Ingegnere industriale (Albo sez. A, dopo l'esame di Stato)", "Progettista meccanico e responsabile dell'ufficio tecnico", "Plant manager e responsabile di produzione", "Energy manager", "Responsabile della trasformazione digitale (Industria 4.0)", "Consulente tecnico e perito"],
        accesso="Serve una laurea triennale di area industriale (tipicamente L-9) o un titolo con i requisiti curricolari richiesti dall'ateneo. Verifichiamo gratuitamente i tuoi crediti prima dell'iscrizione.",
        dopo="Dopo la magistrale: esame di Stato per la sezione A dell'Albo, master di II livello o dottorato di ricerca.",
        faq=[
            ("Ho la triennale L-9: entro direttamente?", "Di norma sì, se il tuo piano di studi soddisfa i requisiti curricolari dell'ateneo. Te lo confermiamo dopo aver visto il certificato degli esami."),
            ("Industria 4.0 è adatto a chi lavora in produzione?", "È l'indirizzo pensato proprio per chi deve digitalizzare impianti e processi: automazione, dati di macchina, manutenzione predittiva."),
            ("Posso studiare lavorando a turni?", "Sì: le lezioni sono registrate e consultabili in qualsiasi momento; il tutor ti aiuta a scegliere gli appelli in base ai turni."),
        ],
        related=["l9", "lm23", "lm32"],
    ),
    "lm23": dict(
        code="LM-23", typ="m", area="ing", years=2, cfu=120,
        url="/corsi-di-laurea/magistrale-ingegneria-civile/",
        name="Ingegneria civile (magistrale)", short="Magistrale Ingegneria Civile LM-23",
        title="Laurea magistrale online in Ingegneria Civile LM-23 | UNICESD",
        desc="Laurea magistrale online in Ingegneria Civile LM-23: strutture e territorio, manutenzione del costruito, opere pubbliche. 120 CFU, accesso all'Albo sez. A.",
        h1="Laurea magistrale in Ingegneria Civile <span class=\"grad\">LM-23</span>",
        lead="Strutture, sicurezza sismica, manutenzione del patrimonio costruito e opere pubbliche: la magistrale per chi vuole progettare e dirigere i lavori con le competenze piene dell'ingegnere.",
        intro=[
            "La magistrale in <b>Ingegneria civile</b> (classe <b>LM-23</b>) completa la formazione dell'ingegnere civile con calcolo strutturale avanzato, ingegneria sismica, geotecnica, infrastrutture e gestione del progetto pubblico, dal bando al collaudo.",
            "Con il titolo magistrale si accede all'esame di Stato per la <b>sezione A dell'Albo degli Ingegneri</b>, settore civile e ambientale.",
        ],
        materie=["Tecnica delle costruzioni avanzata", "Ingegneria sismica", "Dinamica delle strutture", "Geotecnica e fondazioni", "Infrastrutture viarie", "Riabilitazione e consolidamento degli edifici", "Contratti pubblici e project management", "BIM e modellazione"],
        indirizzi=[
            ("Strutture e territorio", "Progettazione strutturale, rischio sismico e idrogeologico, pianificazione del territorio."),
            ("Gestione, manutenzione e controllo del costruito", "Diagnosi, monitoraggio e consolidamento del patrimonio edilizio e infrastrutturale esistente."),
            ("Tecnica e gestione del progetto di opere pubbliche", "Il ciclo dell'opera pubblica: programmazione, progettazione, appalto, direzione lavori e collaudo."),
        ],
        sbocchi=["Ingegnere civile (Albo sez. A, dopo l'esame di Stato)", "Progettista strutturale e direttore dei lavori", "RUP e tecnico nelle stazioni appaltanti", "Responsabile tecnico in imprese di costruzione", "Collaudatore e consulente tecnico", "Esperto di manutenzione e monitoraggio di edifici e infrastrutture"],
        accesso="Serve una laurea triennale di area civile (tipicamente L-7) o un titolo con i requisiti curricolari richiesti dall'ateneo. Valutiamo gratis i tuoi esami prima della domanda.",
        dopo="Esame di Stato per la sezione A dell'Albo, master di II livello in ingegneria strutturale o in appalti, dottorato di ricerca.",
        faq=[
            ("Lavoro in un ufficio tecnico comunale: è il corso giusto?", "Sì, in particolare l'indirizzo sulle opere pubbliche, costruito attorno al ciclo dell'appalto e al ruolo del RUP."),
            ("Che cosa si intende per manutenzione del costruito?", "La parte dell'ingegneria che si occupa degli edifici e delle infrastrutture già esistenti: diagnosi dei degradi, monitoraggio e interventi di consolidamento."),
            ("Posso iscrivermi con una triennale in architettura?", "Dipende dai crediti nei settori dell'ingegneria civile. Ti diciamo con precisione cosa manca e come recuperarlo."),
        ],
        related=["l7", "lm33", "c5"],
    ),
    "lm32": dict(
        code="LM-32", typ="m", area="ing", years=2, cfu=120,
        url="/corsi-di-laurea/magistrale-ingegneria-informatica/",
        name="Ingegneria informatica e dell'automazione (magistrale)", short="Magistrale Ingegneria Informatica LM-32",
        title="Magistrale online in Ingegneria Informatica LM-32 | UNICESD",
        desc="Laurea magistrale online in Ingegneria Informatica LM-32: intelligenza artificiale, robotica e cybersecurity. 120 CFU, esami in sede, tutor dedicato.",
        h1="Laurea magistrale in Ingegneria Informatica <span class=\"grad\">LM-32</span>",
        lead="Intelligenza artificiale, robotica e sicurezza informatica al livello che serve per guidare progetti e team. Due anni online, con esami in sede.",
        intro=[
            "La magistrale in <b>Ingegneria informatica e dell'automazione</b> (classe <b>LM-32</b>) è pensata per chi ha già una triennale tecnica e vuole specializzarsi nelle aree dove la domanda di professionisti supera di molto l'offerta: AI, cybersecurity e automazione.",
            "Il titolo magistrale consente di accedere all'esame di Stato per la <b>sezione A dell'Albo degli Ingegneri</b>, settore dell'informazione.",
        ],
        materie=["Machine learning e deep learning", "Sistemi distribuiti e cloud", "Sicurezza delle reti e dei sistemi", "Robotica e controllo", "Ingegneria del software avanzata", "Big data e basi di dati avanzate", "Sistemi embedded e IoT", "Ottimizzazione e ricerca operativa"],
        indirizzi=[
            ("Base", "Un percorso equilibrato tra software, sistemi e automazione."),
            ("Intelligenza artificiale", "Apprendimento automatico, visione artificiale, elaborazione del linguaggio e sistemi intelligenti."),
            ("Robotica", "Manipolatori, robot mobili, percezione e controllo dei sistemi autonomi."),
            ("Cybersecurity", "Sicurezza delle reti, crittografia, analisi delle minacce, risposta agli incidenti e conformità."),
        ],
        sbocchi=["Ingegnere dell'informazione (Albo sez. A, dopo l'esame di Stato)", "AI engineer e data scientist", "Security engineer e responsabile della sicurezza informatica", "Software architect e tech lead", "Ingegnere dell'automazione e della robotica", "Consulente per la trasformazione digitale e la conformità all'AI Act"],
        accesso="Serve una laurea triennale in ingegneria informatica (L-8) o in area affine con i requisiti curricolari richiesti. Se mancano crediti, si recuperano con i corsi singoli.",
        dopo="Esame di Stato per la sezione A, master di II livello, dottorato di ricerca, oppure ruoli senior in azienda.",
        faq=[
            ("Ho una laurea in informatica (L-31): posso iscrivermi?", "Spesso sì, a condizione di avere i crediti richiesti nei settori dell'ingegneria e della matematica. Facciamo noi la verifica sul tuo certificato."),
            ("Quale indirizzo scelgo se lavoro nell'IT?", "Chi sviluppa software sceglie spesso Intelligenza artificiale; chi lavora su infrastrutture e reti, Cybersecurity. Ne parliamo al colloquio."),
            ("Che differenza c'è con la triennale L-8?", "La <a href=\"/corsi-di-laurea/ingegneria-informatica/\">triennale L-8</a> dà le basi; la magistrale LM-32 specializza e apre alla sezione A dell'Albo."),
        ],
        related=["c5", "lm33", "m5"],
    ),
    # ------------------------------------------------------------------ LETTERE, ARTI E LINGUE
    "l10": dict(
        code="L-10", typ="t", area="let", years=3, cfu=180,
        url="/corsi-di-laurea/lettere/",
        name="Letteratura, arte, musica e spettacolo", short="Lettere L-10",
        title="Laurea online in Lettere L-10: arte, musica, spettacolo",
        desc="Laurea triennale online in Lettere L-10 (Letteratura, arte, musica e spettacolo): indirizzo letterario o artistico-audiovisivo. 180 CFU, esami in sede.",
        h1="Laurea in Lettere online <span class=\"grad\">L-10</span>",
        lead="Letteratura italiana, storia, arte, musica e spettacolo: la laurea umanistica per chi vuole insegnare, scrivere, lavorare nella cultura e nei media.",
        intro=[
            "Il corso in <b>Letteratura, arte, musica e spettacolo</b> appartiene alla classe <b>L-10, Lettere</b>. Accanto alle materie classiche (letteratura italiana, linguistica, storia, geografia) offre un indirizzo dedicato alle arti, al cinema e all'audiovisivo.",
            "È la base per chi punta all'insegnamento delle materie letterarie, dopo la magistrale e il percorso abilitante, e per chi vuole lavorare nell'editoria, nei musei, nello spettacolo e nella comunicazione culturale.",
        ],
        materie=["Letteratura italiana", "Linguistica italiana", "Letteratura latina", "Storia medievale, moderna e contemporanea", "Geografia", "Storia dell'arte", "Storia della musica", "Cinema, fotografia e televisione"],
        indirizzi=[
            ("Letterario", "Letteratura, lingua, storia e geografia: il percorso più indicato per chi pensa all'insegnamento."),
            ("Artistico, audiovisivo e dello spettacolo", "Storia dell'arte, musica, teatro, cinema e linguaggi audiovisivi."),
        ],
        sbocchi=["Redattore e operatore nell'editoria", "Operatore culturale in musei, biblioteche e fondazioni", "Organizzatore di eventi e rassegne culturali", "Content writer e addetto alla comunicazione culturale", "Insegnante, dopo la magistrale e il percorso abilitante", "Collaboratore di produzioni audiovisive e teatrali"],
        accesso="Serve il diploma di scuola secondaria superiore. Non c'è numero chiuso.",
        dopo="Il proseguimento naturale è la <a href=\"/corsi-di-laurea/magistrale-lettere/\">magistrale in Letteratura, lingua e cultura italiana LM-14</a>, necessaria per le classi di concorso di area letteraria.",
        faq=[
            ("Con la triennale in Lettere posso insegnare?", "Per l'insegnamento nella scuola secondaria serve la laurea magistrale con i crediti richiesti dalla classe di concorso e il percorso abilitante previsto dalla normativa. La triennale è il primo passo."),
            ("Quale indirizzo scegliere per l'insegnamento?", "L'indirizzo letterario, perché copre meglio i crediti in letteratura, lingua, storia e geografia richiesti dalle classi di concorso."),
            ("Le lezioni di arte e cinema sono solo teoriche?", "Sono online, con materiali audiovisivi e analisi di opere; molti esami prevedono elaborati su casi concreti."),
        ],
        related=["lm14", "l11", "l3"],
    ),
    "l3": dict(
        code="L-3", typ="t", area="let", years=3, cfu=180,
        url="/corsi-di-laurea/design-moda/",
        name="Design e discipline della moda", short="Design e Moda L-3",
        title="Laurea online in Design e Discipline della Moda (L-3) | UNICESD",
        desc="Laurea triennale online in Design e Discipline della Moda L-3: storia, progettazione, marketing e comunicazione della moda. 180 CFU, esami in sede.",
        h1="Laurea in Design e Discipline della Moda online <span class=\"grad\">L-3</span>",
        lead="La moda come cultura, progetto e industria: un triennio che unisce storia del costume, design, marketing e comunicazione, per lavorare nel sistema moda italiano.",
        intro=[
            "Il corso in <b>Design e discipline della moda</b> (classe <b>L-3</b>, Discipline delle arti figurative, della musica, dello spettacolo e della moda) guarda alla moda da tutti i lati: la storia e la cultura del costume, il processo creativo, la filiera produttiva, il marketing e la comunicazione dei marchi.",
            "Il Made in Italy della moda è una delle eccellenze più riconosciute al mondo: il corso prepara a lavorarci dentro, sia sul lato creativo sia su quello organizzativo e commerciale.",
        ],
        materie=["Storia della moda e del costume", "Storia dell'arte contemporanea", "Fondamenti di design", "Fashion marketing", "Comunicazione e media della moda", "Sociologia dei consumi", "Economia e gestione delle imprese della moda", "Diritto della proprietà industriale"],
        indirizzi=[("Percorso unico", "Un solo percorso che unisce cultura, progetto e mercato della moda.")],
        sbocchi=["Assistente di prodotto e di collezione", "Fashion marketing e brand specialist", "Addetto alla comunicazione e all'ufficio stampa della moda", "Visual merchandiser", "Buyer e addetto al retail", "Organizzatore di eventi e sfilate"],
        accesso="Serve il diploma di scuola secondaria superiore. Non è richiesto un portfolio per l'iscrizione.",
        dopo="Si può proseguire con magistrali in design, comunicazione o management della moda, oppure con master di settore.",
        faq=[
            ("Serve saper disegnare?", "No, non è un requisito d'accesso. Il corso dà le basi del design; chi ha già competenze grafiche le valorizza nei progetti."),
            ("È un corso più creativo o più manageriale?", "È equilibrato: metà cultura e progetto, metà mercato, comunicazione e gestione d'impresa."),
            ("Posso farmi riconoscere un diploma di moda o un ITS?", "I percorsi post diploma possono essere valutati per il riconoscimento dei crediti: mandaci i documenti per una stima gratuita."),
        ],
        related=["l20", "l10", "lm56"],
    ),
    "l11": dict(
        code="L-11", typ="t", area="let", years=3, cfu=180,
        url="/corsi-di-laurea/lingue-culture/",
        name="Lingue e culture europee e del resto del mondo", short="Lingue e Culture L-11",
        title="Laurea online in Lingue e Culture Moderne (L-11) | UNICESD Olympo",
        desc="Laurea triennale online in Lingue e Culture L-11: indirizzi pedagogico-didattico, editoriale, interculturale e computazionale. 180 CFU, esami in sede.",
        h1="Laurea in Lingue e Culture online <span class=\"grad\">L-11</span>",
        lead="Due lingue straniere studiate a fondo, insieme a letterature, culture e strumenti digitali: il triennio per lavorare con le lingue nella scuola, nell'editoria, nelle imprese e nel turismo.",
        intro=[
            "Il corso in <b>Lingue e culture europee e del resto del mondo</b> (classe <b>L-11</b>, Lingue e culture moderne) forma laureati capaci di usare due lingue straniere a un livello avanzato e di conoscerne le letterature e le culture.",
            "Quattro indirizzi lo orientano verso sbocchi diversi: l'insegnamento, l'editoria multimediale, la mediazione interculturale e le tecnologie del linguaggio.",
        ],
        materie=["Lingua e traduzione (due lingue a scelta)", "Letterature straniere", "Linguistica generale", "Glottodidattica", "Letteratura italiana", "Storia e culture dei Paesi studiati", "Informatica per le lingue", "Comunicazione interculturale"],
        indirizzi=[
            ("Pedagogico-didattico", "Glottodidattica e metodologie per chi pensa all'insegnamento delle lingue."),
            ("Tecnico computazionale", "Linguistica computazionale, traduzione assistita e strumenti di intelligenza artificiale per le lingue."),
            ("Editoriale-multimediale", "Lingue applicate all'editoria, alla redazione e ai contenuti digitali."),
            ("Comunicazione interculturale", "Mediazione tra culture in aziende, enti, servizi per migranti e cooperazione internazionale."),
        ],
        sbocchi=["Esperto linguistico nelle imprese e nel commercio internazionale", "Redattore e traduttore nell'editoria", "Mediatore interculturale", "Operatore nel turismo e nell'accoglienza internazionale", "Insegnante di lingue, dopo la magistrale e il percorso abilitante", "Specialista di contenuti multilingue e localizzazione"],
        accesso="Serve il diploma di scuola secondaria superiore. È consigliata una conoscenza di base delle lingue scelte; il livello di partenza viene verificato senza effetti sull'iscrizione.",
        dopo="Si prosegue con la <a href=\"/corsi-di-laurea/magistrale-lingue-traduzione/\">magistrale in Lingue e letterature moderne e traduzione LM-37</a>; per certificare il livello sono utili anche le <a href=\"/certificazioni/linguistiche/\">certificazioni linguistiche</a>.",
        faq=[
            ("Quali lingue si possono studiare?", "Le lingue attivate dipendono dall'anno accademico: di norma inglese, francese, spagnolo e tedesco. Te le confermiamo al colloquio."),
            ("È utile una certificazione linguistica?", "Sì, sia per il curriculum sia, in alcuni casi, per il riconoscimento di crediti. Possiamo prepararti anche alla certificazione."),
            ("Che differenza c'è tra L-11 e mediazione linguistica L-12?", "La L-11 dà più spazio a letterature e culture; la L-12 è più centrata su traduzione e interpretariato."),
        ],
        related=["lm37", "l10", "l15"],
    ),
    "lm14": dict(
        code="LM-14", typ="m", area="let", years=2, cfu=120,
        url="/corsi-di-laurea/magistrale-lettere/",
        name="Letteratura, lingua e cultura italiana (magistrale)", short="Magistrale Lettere LM-14",
        title="Laurea magistrale online in Lettere (LM-14) | UNICESD Olympo",
        desc="Laurea magistrale online in Letteratura, Lingua e Cultura Italiana LM-14: indirizzo filologico o di promozione culturale. 120 CFU, utile per l'insegnamento.",
        h1="Laurea magistrale in Lettere <span class=\"grad\">LM-14</span>",
        lead="La magistrale in filologia, letteratura e cultura italiana: il titolo che serve per insegnare materie letterarie e per lavorare ai livelli più alti dell'editoria e della cultura.",
        intro=[
            "La magistrale in <b>Letteratura, lingua e cultura italiana</b> (classe <b>LM-14</b>, Filologia moderna) approfondisce la letteratura italiana dalle origini al Novecento, la storia della lingua, la filologia e la critica.",
            "Per chi vuole insegnare è uno dei titoli d'accesso alle classi di concorso di area letteraria (come A-22, A-12 e A-11), purché il percorso complessivo comprenda i crediti richiesti dalla normativa sulle classi di concorso e si completi il percorso abilitante.",
        ],
        materie=["Letteratura italiana medievale, moderna e contemporanea", "Filologia italiana", "Storia della lingua italiana", "Letteratura latina", "Critica letteraria e teoria della letteratura", "Didattica dell'italiano", "Storia", "Geografia"],
        indirizzi=[
            ("Promozione culturale", "Letteratura e cultura italiana applicate a editoria, musei, eventi e comunicazione culturale."),
            ("Filologico", "Edizione e analisi dei testi, storia della lingua: il percorso più tradizionale e più vicino all'insegnamento e alla ricerca."),
        ],
        sbocchi=["Docente di materie letterarie (con i requisiti della classe di concorso e l'abilitazione)", "Editor e redattore", "Esperto di promozione culturale e progettazione di eventi", "Operatore di biblioteche, archivi e istituti culturali", "Critico e giornalista culturale", "Dottorato di ricerca e carriera accademica"],
        accesso="Serve una laurea triennale (tipicamente L-10) con i requisiti curricolari richiesti dall'ateneo nei settori letterari, linguistici e storici. Ti diciamo in anticipo se ti mancano crediti e come colmarli.",
        dopo="Con la magistrale e i crediti richiesti si accede al percorso abilitante all'insegnamento; in alternativa dottorato di ricerca, master in editoria o in didattica.",
        faq=[
            ("Con questa magistrale posso insegnare italiano alle medie?", "La classe A-22 (italiano, storia e geografia nella secondaria di I grado) è tra quelle a cui la LM-14 dà accesso, se nel percorso hai i crediti richiesti. Ti aiutiamo a verificare il tuo piano di studi."),
            ("Mi mancano CFU per la classe di concorso: che faccio?", "Li puoi recuperare con i <a href=\"/corsi-singoli-cfu/\">corsi singoli</a>, anche dopo la laurea."),
            ("Quale indirizzo è più adatto all'insegnamento?", "L'indirizzo filologico, più centrato su lingua, testi e storia della letteratura."),
        ],
        related=["l10", "lm37", "m3"],
    ),
    "lm37": dict(
        code="LM-37", typ="m", area="let", years=2, cfu=120,
        url="/corsi-di-laurea/magistrale-lingue-traduzione/",
        name="Lingue e letterature moderne e traduzione interculturale (magistrale)", short="Magistrale Lingue LM-37",
        title="Laurea magistrale online in Lingue e Traduzione LM-37 | UNICESD",
        desc="Laurea magistrale online in Lingue e Letterature Moderne e Traduzione LM-37: indirizzo letterature europee o traduzione. 120 CFU, esami in sede.",
        h1="Laurea magistrale in Lingue e Traduzione <span class=\"grad\">LM-37</span>",
        lead="Due lingue al livello più alto, letterature europee e traduzione: la magistrale per chi vuole insegnare lingue, tradurre o lavorare in contesti internazionali.",
        intro=[
            "La magistrale in <b>Lingue e letterature moderne e traduzione interculturale</b> (classe <b>LM-37</b>, Lingue e letterature moderne europee e americane) porta le competenze linguistiche al livello professionale e approfondisce le letterature dei Paesi studiati.",
            "È uno dei titoli che, con i crediti richiesti e il percorso abilitante, danno accesso alle classi di concorso per l'insegnamento delle lingue straniere nella scuola secondaria.",
        ],
        materie=["Lingua e traduzione avanzata (due lingue)", "Letterature europee e americane", "Teoria e tecnica della traduzione", "Traduzione specialistica e audiovisiva", "Linguistica contrastiva", "Didattica delle lingue moderne", "Strumenti digitali per la traduzione", "Studi culturali"],
        indirizzi=[
            ("Lingue e letterature europee", "Letterature e culture dei Paesi europei e americani, con attenzione all'insegnamento e alla ricerca."),
            ("Traduzione e processi interlinguistici", "Traduzione letteraria, tecnica e audiovisiva, revisione e uso degli strumenti CAT e di traduzione automatica."),
        ],
        sbocchi=["Docente di lingua straniera (con i requisiti della classe di concorso e l'abilitazione)", "Traduttore e revisore editoriale e tecnico", "Localizzatore e specialista di contenuti multilingue", "Esperto linguistico in organismi internazionali e imprese", "Operatore culturale e dell'editoria", "Dottorato e ricerca"],
        accesso="Serve una laurea triennale (tipicamente L-11 o L-12) con i requisiti curricolari dell'ateneo nelle lingue scelte.",
        dopo="Percorso abilitante all'insegnamento, master in traduzione specialistica, dottorato di ricerca.",
        faq=[
            ("Posso diventare traduttore con questa laurea?", "Sì, l'indirizzo in traduzione è pensato per questo: letteraria, tecnica e audiovisiva, con gli strumenti professionali del settore."),
            ("Serve una certificazione linguistica per iscriversi?", "Non sempre, ma aiuta a dimostrare il livello. Possiamo prepararti alla <a href=\"/certificazioni/linguistiche/\">certificazione</a>."),
            ("Posso insegnare inglese con la LM-37?", "La LM-37 è tra i titoli d'accesso alle classi di concorso di lingua straniera, se nel percorso ci sono i crediti richiesti per quella lingua."),
        ],
        related=["l11", "lm14", "k2"],
    ),
    # ------------------------------------------------------------------ PEDAGOGIA
    "lm85": dict(
        code="LM-85", typ="m", area="ped", years=2, cfu=120,
        url="/corsi-di-laurea/magistrale-scienze-pedagogiche/",
        name="Scienze pedagogiche (magistrale)", short="Magistrale Scienze Pedagogiche LM-85",
        title="Laurea magistrale online in Scienze Pedagogiche LM-85 | UNICESD",
        desc="Laurea magistrale online in Scienze Pedagogiche LM-85 per diventare pedagogista: marginalità e disabilità, e-learning e media education. 120 CFU.",
        h1="Laurea magistrale in Scienze Pedagogiche <span class=\"grad\">LM-85</span>",
        lead="La magistrale per diventare pedagogista: coordinare servizi educativi, progettare interventi per la disabilità e la marginalità, guidare la formazione anche digitale.",
        intro=[
            "La magistrale in <b>Scienze pedagogiche</b> (classe <b>LM-85</b>) forma il <b>pedagogista</b>, la figura che progetta, coordina e valuta i servizi educativi e formativi. Con la legge 55/2024 le professioni di pedagogista ed educatore professionale socio-pedagogico sono state ordinate in albi professionali.",
            "Il corso è la prosecuzione naturale della triennale in <a href=\"/corsi-di-laurea/scienze-educazione/\">Scienze dell'educazione L-19</a> ed è molto scelto da educatori e insegnanti che vogliono assumere ruoli di coordinamento.",
        ],
        materie=["Pedagogia generale e sociale", "Pedagogia speciale e dell'inclusione", "Progettazione e valutazione dei servizi educativi", "Psicologia dell'educazione", "Sociologia dell'educazione", "Tecnologie dell'istruzione e dell'apprendimento", "Filosofia dell'educazione", "Metodologia della ricerca educativa"],
        indirizzi=[
            ("Pedagogia e scienze umane", "Il percorso generale: teorie, storia e ricerca educativa."),
            ("Pedagogista della marginalità e della disabilità", "Inclusione, disabilità, devianza, povertà educativa e servizi socio-educativi."),
            ("E-learning, didattica digitale e media education", "Progettazione di percorsi online, educazione ai media e formazione degli adulti."),
        ],
        sbocchi=["Pedagogista (con l'iscrizione all'albo prevista dalla legge 55/2024)", "Coordinatore di servizi educativi e per l'infanzia", "Responsabile di servizi socio-educativi e per la disabilità", "Progettista della formazione e instructional designer", "Consulente pedagogico per scuole, famiglie e aziende", "Formatore nella formazione degli adulti e aziendale"],
        accesso="Serve una laurea triennale (tipicamente L-19) o un titolo con i requisiti curricolari richiesti nei settori pedagogici, psicologici e sociologici.",
        dopo="Iscrizione all'albo dei pedagogisti secondo la normativa, master in coordinamento dei servizi o in didattica, dottorato di ricerca.",
        faq=[
            ("Che differenza c'è tra educatore e pedagogista?", "L'educatore (laurea L-19) lavora direttamente con le persone nei servizi; il pedagogista (laurea LM-85) progetta, coordina, supervisiona e fa consulenza."),
            ("Sono insegnante: mi serve la LM-85?", "Non per insegnare, ma è utile per ruoli di coordinamento, per la funzione strumentale sull'inclusione e per la consulenza pedagogica."),
            ("Posso iscrivermi con una laurea in psicologia?", "Spesso sì, se hai i crediti richiesti nei settori pedagogici; altrimenti li integri con i corsi singoli."),
        ],
        related=["c4", "lm51", "m3"],
    ),
    # ------------------------------------------------------------------ PSICOLOGIA
    "lm51": dict(
        code="LM-51", typ="m", area="psi", years=2, cfu=120,
        url="/corsi-di-laurea/magistrale-psicologia/",
        name="Psicologia (magistrale)", short="Magistrale Psicologia LM-51",
        title="Laurea magistrale online in Psicologia LM-51 | UNICESD Olympo",
        desc="Laurea magistrale online in Psicologia LM-51: clinica e dinamica, giuridica e criminologia, nuove tecnologie, psicologia strategica. 120 CFU, abilitante.",
        h1="Laurea magistrale in Psicologia <span class=\"grad\">LM-51</span>",
        lead="La magistrale che porta alla professione di psicologo: quattro indirizzi, tirocinio pratico-valutativo e didattica online, con un tutor che ti segue fino alla laurea.",
        intro=[
            "La magistrale in <b>Psicologia</b> (classe <b>LM-51</b>) completa la formazione iniziata con la <a href=\"/corsi-di-laurea/scienze-psicologiche/\">triennale L-24</a>. Con la riforma introdotta dalla legge 163/2021 la laurea magistrale in Psicologia è <b>abilitante</b>: comprende un tirocinio pratico-valutativo e la prova finale abilita all'esercizio della professione, con l'iscrizione all'Albo degli Psicologi.",
            "Quattro indirizzi permettono di orientarsi da subito verso l'ambito in cui si vuole lavorare: clinico, giuridico-forense, delle tecnologie o della psicologia strategica.",
        ],
        materie=["Psicologia clinica", "Psicopatologia", "Psicologia dinamica", "Valutazione psicologica e testistica", "Psicologia della salute", "Psicologia giuridica", "Neuropsicologia", "Metodi di ricerca in psicologia"],
        indirizzi=[
            ("Psicologia clinica e dinamica", "Diagnosi, colloquio clinico e modelli di intervento: il percorso per chi pensa alla psicoterapia."),
            ("Psicologia giuridica e criminologia", "Perizie, valutazione in ambito civile e penale, vittimologia, psicologia investigativa."),
            ("Psicologia e nuove tecnologie", "Benessere digitale, dipendenze tecnologiche, interventi online, psicologia dell'interazione uomo-macchina."),
            ("Psicologia strategica", "Problem solving, comunicazione strategica e interventi brevi nei contesti clinici e organizzativi."),
        ],
        sbocchi=["Psicologo (iscrizione all'Albo dopo la laurea abilitante)", "Psicologo clinico in servizi pubblici e privati", "Psicologo giuridico e consulente tecnico", "Psicologo del lavoro e delle organizzazioni", "Esperto di benessere digitale e interventi online", "Accesso alle scuole di specializzazione in psicoterapia"],
        accesso="Serve una laurea triennale in Scienze e tecniche psicologiche (L-24) o un titolo con i crediti richiesti nei settori della psicologia. Verifichiamo gratuitamente il tuo piano di studi.",
        dopo="Iscrizione all'Albo degli Psicologi, scuole di specializzazione in psicoterapia (quadriennali), master di II livello.",
        faq=[
            ("La magistrale online è abilitante come quella in presenza?", "Sì: la natura abilitante dipende dalla classe di laurea LM-51 e dall'ordinamento dell'ateneo, non dalla modalità di erogazione. Il tirocinio pratico-valutativo si svolge presso enti convenzionati."),
            ("Dove si fa il tirocinio?", "Presso strutture convenzionate con l'ateneo; ti aiutiamo a individuarne una vicino a dove vivi."),
            ("Quale indirizzo per diventare psicoterapeuta?", "Psicologia clinica e dinamica è il più vicino, ma l'accesso alle scuole di psicoterapia è aperto a tutti gli psicologi iscritti all'Albo."),
        ],
        related=["c3", "lm85", "l14"],
    ),
    # ------------------------------------------------------------------ BIOLOGIA E NUTRIZIONE
    "l13": dict(
        code="L-13", typ="t", area="bio", years=3, cfu=180,
        url="/corsi-di-laurea/scienze-biologiche/",
        name="Scienze biologiche", short="Scienze Biologiche L-13",
        title="Laurea online in Scienze Biologiche (L-13) | UNICESD Olympo",
        desc="Laurea triennale online in Scienze Biologiche L-13: indirizzo biosanitario e molecolare o ambiente e biodiversità. 180 CFU, esami e laboratori in sede.",
        h1="Laurea in Scienze Biologiche online <span class=\"grad\">L-13</span>",
        lead="Dalla cellula agli ecosistemi: la triennale in biologia per chi vuole lavorare nei laboratori, nella sanità, nell'ambiente o proseguire verso la nutrizione.",
        intro=[
            "Il corso in <b>Scienze biologiche</b> (classe <b>L-13</b>) dà una formazione completa sulla vita a tutti i livelli: biochimica, genetica, microbiologia, fisiologia, ecologia. La parte teorica si segue online; le attività di laboratorio e gli esami si svolgono secondo le modalità previste dall'ateneo.",
            "È la base per accedere alle magistrali biologiche, compresa quella in <a href=\"/corsi-di-laurea/magistrale-scienze-nutrizione/\">Scienze della nutrizione umana LM-61</a>.",
        ],
        materie=["Chimica generale e organica", "Biologia cellulare e molecolare", "Biochimica", "Genetica", "Microbiologia", "Fisiologia", "Ecologia", "Botanica e zoologia"],
        indirizzi=[
            ("Biosanitario e molecolare", "Biologia applicata alla salute: biotecnologie, diagnostica di laboratorio, biologia molecolare."),
            ("Ambiente e biodiversità", "Ecologia, conservazione della natura, monitoraggio ambientale e gestione delle risorse."),
        ],
        sbocchi=["Biologo iunior (Albo sez. B, secondo la normativa)", "Tecnico di laboratorio di analisi e di ricerca", "Addetto al controllo qualità in industrie alimentari e farmaceutiche", "Tecnico del monitoraggio ambientale", "Informatore scientifico", "Proseguimento verso la nutrizione e le magistrali biologiche"],
        accesso="Serve il diploma di scuola secondaria superiore. La verifica delle conoscenze di base di chimica, biologia e matematica non è selettiva.",
        dopo="Magistrale in Scienze della nutrizione umana LM-61 o altre magistrali biologiche; master in sicurezza alimentare e ambientale.",
        faq=[
            ("I laboratori si fanno online?", "La teoria sì; le attività pratiche si svolgono nelle modalità e nelle sedi indicate dall'ateneo. Ti diamo il calendario al momento dell'iscrizione."),
            ("Con la triennale posso fare il nutrizionista?", "No: per l'attività di biologo nutrizionista serve una laurea magistrale come la LM-61 e l'iscrizione all'albo secondo la normativa vigente."),
            ("Quale indirizzo per lavorare in un laboratorio di analisi?", "L'indirizzo biosanitario e molecolare."),
        ],
        related=["lm61", "lm67", "c6"],
    ),
    "lm61": dict(
        code="LM-61", typ="m", area="bio", years=2, cfu=120,
        url="/corsi-di-laurea/magistrale-scienze-nutrizione/",
        name="Scienze della nutrizione umana (magistrale)", short="Magistrale Nutrizione LM-61",
        title="Magistrale online in Scienze della Nutrizione LM-61 | UNICESD",
        desc="Laurea magistrale online in Scienze della Nutrizione Umana LM-61: nutrizione molecolare, chimica e marketing degli alimenti. 120 CFU, verso il biologo nutrizionista.",
        h1="Laurea magistrale in Scienze della Nutrizione <span class=\"grad\">LM-61</span>",
        lead="La magistrale per chi vuole lavorare con l'alimentazione: nutrizione clinica e sportiva, alimenti funzionali, industria alimentare. Online, con esami in sede.",
        intro=[
            "La magistrale in <b>Scienze della nutrizione umana</b> (classe <b>LM-61</b>) studia il rapporto tra alimentazione e salute, dalla biochimica dei nutrienti alla dietetica applicata, fino alla progettazione di prodotti alimentari.",
            "È uno dei percorsi che consentono di arrivare alla professione di <b>biologo nutrizionista</b>, con l'iscrizione all'Albo dei Biologi nei modi previsti dalla normativa vigente.",
        ],
        materie=["Biochimica della nutrizione", "Fisiologia della nutrizione", "Dietetica e nutrizione clinica", "Nutrizione nello sport", "Chimica degli alimenti", "Tecnologie alimentari", "Igiene e sicurezza degli alimenti", "Nutrigenomica"],
        indirizzi=[
            ("Nutrizione molecolare", "Il rapporto tra nutrienti, geni e metabolismo: nutrigenomica, microbiota, prevenzione."),
            ("Chimica, tecnologia e marketing", "Gli alimenti dal laboratorio allo scaffale: composizione, processi, etichettatura e mercato."),
        ],
        sbocchi=["Biologo nutrizionista (con l'iscrizione all'albo secondo la normativa)", "Nutrizionista sportivo in collaborazione con società e centri", "Consulente per industrie alimentari e integratori", "Addetto alla ricerca e sviluppo di prodotti alimentari", "Esperto di sicurezza alimentare e qualità", "Educatore alimentare in scuole, enti e aziende"],
        accesso="Serve una laurea triennale di area biologica, biotecnologica, delle scienze dell'alimentazione o affine, con i requisiti curricolari richiesti dall'ateneo.",
        dopo="Iscrizione all'albo secondo la normativa, master in nutrizione clinica o sportiva, dottorato.",
        faq=[
            ("Ho una laurea in scienze motorie: posso iscrivermi?", "Dipende dai crediti in chimica, biochimica e biologia: in molti casi servono alcuni corsi singoli integrativi. Facciamo noi la verifica."),
            ("Posso fare piani alimentari dopo la laurea?", "L'elaborazione di diete è un'attività riservata a specifiche figure professionali abilitate: ti spieghiamo i passaggi per l'iscrizione all'albo."),
            ("C'è un legame con la ricerca sul microbiota?", "Sì, l'indirizzo in nutrizione molecolare affronta anche microbiota e nutrigenomica."),
        ],
        related=["l13", "lm67", "c6"],
    ),
    # ------------------------------------------------------------------ SCIENZE MOTORIE
    "lm67": dict(
        code="LM-67", typ="m", area="mot", years=2, cfu=120,
        url="/corsi-di-laurea/magistrale-scienze-motorie/",
        name="Scienze dell'esercizio fisico per il benessere e la salute (magistrale)", short="Magistrale Scienze Motorie LM-67",
        title="Laurea magistrale online in Scienze Motorie LM-67 | UNICESD Olympo",
        desc="Laurea magistrale online in Scienze Motorie LM-67: attività motoria preventiva e adattata, scuola secondaria, biomeccanica, palestra del benessere. 120 CFU.",
        h1="Laurea magistrale in Scienze Motorie <span class=\"grad\">LM-67</span>",
        lead="Attività motoria per la salute, la prevenzione e la scuola: la magistrale per chinesiologi e laureati in scienze motorie che vogliono crescere professionalmente o insegnare.",
        intro=[
            "La magistrale in <b>Scienze dell'esercizio fisico per il benessere e la salute</b> (classe <b>LM-67</b>, Scienze e tecniche delle attività motorie preventive e adattate) forma professionisti capaci di progettare l'esercizio fisico per la prevenzione, per le persone anziane e per chi ha patologie croniche stabilizzate o disabilità.",
            "La LM-67 è anche tra i titoli che, con i crediti richiesti e il percorso abilitante, danno accesso alla classe di concorso A-48 (Scienze motorie e sportive negli istituti di istruzione secondaria).",
        ],
        materie=["Attività motoria preventiva e adattata", "Fisiologia dell'esercizio", "Biomeccanica del movimento", "Valutazione funzionale", "Metodologia dell'allenamento per la salute", "Didattica delle attività motorie", "Pedagogia speciale", "Nutrizione e attività fisica"],
        indirizzi=[
            ("Attività motoria nella scuola secondaria", "Didattica e metodologie per chi punta all'insegnamento di scienze motorie."),
            ("Biomeccanica", "Analisi del movimento, prevenzione degli infortuni, strumenti di misura."),
            ("Palestra del benessere", "Programmi di esercizio per salute, anziani e popolazioni speciali, gestione di centri fitness e wellness."),
        ],
        sbocchi=["Chinesiologo delle attività motorie preventive e adattate", "Docente di scienze motorie (con i requisiti della classe di concorso e l'abilitazione)", "Responsabile tecnico di palestre e centri benessere", "Esperto di esercizio fisico per anziani e persone con patologie croniche", "Analista del movimento e consulente biomeccanico", "Coordinatore di progetti di promozione della salute"],
        accesso="Serve una laurea triennale in <a href=\"/corsi-di-laurea/scienze-motorie/\">Scienze motorie L-22</a> o un titolo con i requisiti curricolari richiesti dall'ateneo.",
        dopo="Percorso abilitante all'insegnamento, master in preparazione atletica o riabilitazione motoria, dottorato.",
        faq=[
            ("Con la LM-67 posso insegnare educazione fisica?", "La LM-67 è tra i titoli d'accesso alla classe A-48, se hai i crediti richiesti; poi serve il percorso abilitante previsto dalla normativa."),
            ("Lavoro in palestra: quale indirizzo scelgo?", "Palestra del benessere, pensato per programmi di esercizio orientati alla salute e alla gestione di centri fitness."),
            ("Che cosa vuol dire attività motoria adattata?", "Esercizio fisico progettato per persone con disabilità, patologie croniche stabilizzate o in età avanzata, in collaborazione con le figure sanitarie."),
        ],
        related=["c6", "lm61", "l13"],
    ),
}

# Hub triennali / magistrali (parola chiave diversa dall'hub "corsi di laurea online")
HUB_TM = {
    "t": dict(url="/lauree-triennali-online/", name="Lauree triennali online",
              title="Lauree triennali online: 15 corsi da 180 CFU | UNICESD Olympo",
              desc="Tutte le lauree triennali online di UNICESD Olympo: economia, giurisprudenza, ingegneria, psicologia, comunicazione, lingue, biologia. Orientamento gratuito.",
              h1="Lauree triennali <span class=\"grad\">online</span>",
              eyebrow="Laurea di primo livello · 3 anni · 180 CFU",
              lead="Quindici corsi di laurea di primo livello, per chi ha il diploma e vuole un titolo universitario studiando online: lezioni sempre disponibili, esami nelle sedi convenzionate e un tutor dall'iscrizione alla laurea.",
              intro="La <b>laurea triennale</b> è il primo livello dell'università italiana: dura tre anni e vale 180 crediti formativi (CFU). Per iscriversi basta il diploma di scuola superiore; nei corsi online non c'è numero chiuso. Con la triennale si può entrare nel mondo del lavoro, partecipare ai concorsi che chiedono la laurea e proseguire con una magistrale. Se hai già esami o esperienze professionali, chiedi la <a href=\"/riconoscimento-cfu/\">valutazione gratuita dei CFU</a>: il percorso può accorciarsi."),
    "m": dict(url="/lauree-magistrali-online/", name="Lauree magistrali online",
              title="Lauree magistrali online: 10 corsi da 120 CFU | UNICESD Olympo",
              desc="Lauree magistrali online di UNICESD Olympo: psicologia, ingegneria, economia, pedagogia, lettere, lingue, nutrizione e scienze motorie. Verifica requisiti gratuita.",
              h1="Lauree magistrali <span class=\"grad\">online</span>",
              eyebrow="Laurea di secondo livello · 2 anni · 120 CFU",
              lead="Dieci lauree magistrali biennali, più Giurisprudenza a ciclo unico, per chi ha già una triennale e vuole specializzarsi, accedere agli albi professionali o all'insegnamento.",
              intro="La <b>laurea magistrale</b> è il secondo livello: dura due anni e vale 120 CFU. Per iscriversi serve una laurea triennale con i <b>requisiti curricolari</b> richiesti dall'ateneo, cioè un certo numero di crediti in settori specifici. Prima della domanda verifichiamo gratuitamente il tuo certificato degli esami e, se mancano crediti, ti indichiamo i <a href=\"/corsi-singoli-cfu/\">corsi singoli</a> per recuperarli."),
}
