# -*- coding: utf-8 -*-
"""
Contenuti delle pagine dedicate del sito online (repo-github).
Qui stanno solo i testi: URL, title, description, H1, introduzione e sezioni.
Il motore che le genera e' build_pages.py.

Regole:
- title        ~50-60 caratteri, parola chiave in testa, marchio in coda
- description  ~140-160 caratteri, frase leggibile con un invito all'azione
- h1           uno solo per pagina, diverso dal title
- sezioni      id delle <section> di body.html riusate cosi' come sono
"""

SITE = "https://unicesd-olympo.com"

# ---------------------------------------------------------------------------
# Corsi: una scheda per ogni voce dell'offerta (i testi completi arrivano dai
# modali DATA di script.html, che da soli Google non vede).
# ---------------------------------------------------------------------------
COURSES = {
    # --- lauree ---
    "c1": dict(url="/corsi-di-laurea/giurisprudenza/", hub="lauree",
               name="Giurisprudenza", short="Giurisprudenza LMG-01",
               title="Laurea online in Giurisprudenza (LMG-01) | UNICESD Olympo",
               desc="Laurea magistrale a ciclo unico in Giurisprudenza LMG-01 online: 5 anni, 300 CFU, esami in sede e tutor dedicato. Riconoscimento CFU gratuito.",
               h1="Laurea in Giurisprudenza online <span class=\"grad\">LMG-01</span>",
               lead="Il percorso magistrale a ciclo unico per avvocatura, magistratura, notariato e pubblica amministrazione, da seguire online con un tutor UNICESD Olympo al tuo fianco e gli esami nelle sedi convenzionate.",
               credits=300, years=5, level="Laurea magistrale a ciclo unico", code="LMG-01"),
    "c2": dict(url="/corsi-di-laurea/economia-aziendale/", hub="lauree",
               name="Economia Aziendale", short="Economia Aziendale L-18",
               title="Laurea online in Economia Aziendale (L-18) | UNICESD Olympo",
               desc="Laurea triennale online in Economia Aziendale, classe L-18: 3 anni, 180 CFU, esami in sede, tutor dedicato e valutazione gratuita dei crediti.",
               h1="Laurea in Economia Aziendale online <span class=\"grad\">L-18</span>",
               lead="Gestione d'impresa, bilancio, controllo di gestione e marketing in un triennio pensato anche per chi lavora: lezioni sempre disponibili, esami in sede e un referente unico per tutto il percorso.",
               credits=180, years=3, level="Laurea triennale", code="L-18"),
    "c3": dict(url="/corsi-di-laurea/scienze-psicologiche/", hub="lauree",
               name="Scienze e Tecniche Psicologiche", short="Scienze Psicologiche L-24",
               title="Laurea online in Scienze Psicologiche (L-24) | UNICESD Olympo",
               desc="Laurea triennale online in Scienze e Tecniche Psicologiche, classe L-24: 180 CFU, accesso alla magistrale LM-51. Orientamento e tutor dedicato.",
               h1="Laurea in Scienze Psicologiche online <span class=\"grad\">L-24</span>",
               lead="Psicologia generale, dello sviluppo, sociale e del lavoro, psicometria e neuroscienze cognitive: il primo passo verso la magistrale LM-51 e la professione di psicologo.",
               credits=180, years=3, level="Laurea triennale", code="L-24"),
    "c4": dict(url="/corsi-di-laurea/scienze-educazione/", hub="lauree",
               name="Scienze dell'Educazione", short="Scienze dell'Educazione L-19",
               title="Laurea online in Scienze dell'Educazione (L-19) | UNICESD Olympo",
               desc="Laurea triennale online in Scienze dell'Educazione, classe L-19: 180 CFU per diventare educatore nei servizi per l'infanzia e socio-educativi.",
               h1="Laurea in Scienze dell'Educazione online <span class=\"grad\">L-19</span>",
               lead="Il corso che forma gli educatori dei servizi per l'infanzia, del sociale e dei contesti formativi extrascolastici, con didattica online ed esami nelle sedi convenzionate.",
               credits=180, years=3, level="Laurea triennale", code="L-19"),
    "c5": dict(url="/corsi-di-laurea/ingegneria-informatica/", hub="lauree",
               name="Ingegneria Informatica", short="Ingegneria Informatica L-8",
               title="Laurea online in Ingegneria Informatica (L-8) | UNICESD Olympo",
               desc="Laurea triennale online in Ingegneria Informatica, classe L-8: programmazione, reti, basi di dati e intelligenza artificiale. 180 CFU, tutor dedicato.",
               h1="Laurea in Ingegneria Informatica online <span class=\"grad\">L-8</span>",
               lead="Programmazione, architetture, reti, basi di dati e intelligenza artificiale applicata: un triennio tecnico da seguire online, con esami in sede e affiancamento personale.",
               credits=180, years=3, level="Laurea triennale", code="L-8"),
    "c6": dict(url="/corsi-di-laurea/scienze-motorie/", hub="lauree",
               name="Scienze Motorie", short="Scienze Motorie L-22",
               title="Laurea online in Scienze Motorie (L-22) | UNICESD Olympo",
               desc="Laurea triennale online in Scienze Motorie, classe L-22: 180 CFU su attività motoria preventiva, sportiva e adattata. Esami in sede e tutor dedicato.",
               h1="Laurea in Scienze Motorie online <span class=\"grad\">L-22</span>",
               lead="Anatomia, fisiologia, metodologia dell'allenamento e management dello sport per lavorare come preparatore, tecnico o operatore nei centri sportivi.",
               credits=180, years=3, level="Laurea triennale", code="L-22"),
    # --- master ---
    "m1": dict(url="/master-made-in-italy-global-leadership/", hub="master",
               name="Made in Italy Global Leadership", short="Master Made in Italy",
               title="Master Made in Italy Global Leadership in Export | UNICESD Olympo",
               desc="Executive Master di I livello in Export, Geopolitics & International Business: 60 CFU, 1500 ore, modalità blended. Avvio A.A. 2026/2027. Candidati.",
               h1="Master <span class=\"tric\">Made in Italy</span> Global Leadership",
               lead="L'Executive Master universitario di I livello in Export, Geopolitics &amp; International Business nato dal protocollo d'intesa firmato a Villa Niscemi, Palermo, nell'agosto 2026: per i manager che portano l'eccellenza italiana sui mercati internazionali.",
               credits=60, hours=1500, level="Master universitario di I livello", code="Executive",
               sections=["master"]),
    "m2": dict(url="/master-universitari/management-imprese-turistiche/", hub="master",
               name="Management delle Imprese Turistiche", short="Master Management Turistico",
               title="Master in Management delle Imprese Turistiche | UNICESD Olympo",
               desc="Master universitario di I livello online in Management delle Imprese Turistiche: destination management, hospitality e turismo esperienziale. 60 CFU.",
               h1="Master in Management delle <span class=\"grad\">Imprese Turistiche</span>",
               lead="Destination management, revenue management, hospitality e turismo esperienziale e sostenibile, con un'attenzione particolare al patrimonio culturale e naturalistico italiano.",
               credits=60, hours=1500, level="Master universitario di I livello"),
    "m3": dict(url="/master-universitari/didattica-innovazione-digitale/", hub="master",
               name="Didattica e Innovazione Digitale", short="Master Didattica Digitale",
               title="Master in Didattica e Innovazione Digitale online | UNICESD",
               desc="Master di I livello online in Didattica e Innovazione Digitale per docenti ed educatori: 60 CFU, 1500 ore, valutabile nelle graduatorie della scuola.",
               h1="Master in Didattica e <span class=\"grad\">Innovazione Digitale</span>",
               lead="Il master per docenti ed educatori che vogliono aggiornare metodi e strumenti: didattica attiva, tecnologie e AI in classe, inclusione, DSA e BES, valutazione per competenze.",
               credits=60, hours=1500, level="Master universitario di I livello"),
    "m4": dict(url="/master-universitari/diritto-impresa-internazionale/", hub="master",
               name="Diritto dell'Impresa Internazionale", short="Master Diritto Internazionale",
               title="Master II livello in Diritto dell'Impresa Internazionale | UNICESD",
               desc="Master universitario di II livello online in Diritto dell'Impresa Internazionale: contratti, arbitrato, compliance 231 e fiscalità transfrontaliera.",
               h1="Master di II livello in <span class=\"grad\">Diritto dell'Impresa Internazionale</span>",
               lead="Alta specializzazione giuridica per chi lavora in contesti transnazionali: contrattualistica internazionale, arbitrato, compliance e fiscalità transfrontaliera.",
               credits=60, hours=1500, level="Master universitario di II livello"),
    "m5": dict(url="/master-universitari/data-analytics-business/", hub="master",
               name="Data Analytics per il Business", short="Data Analytics",
               title="Corso di alta formazione in Data Analytics per il Business | UNICESD",
               desc="Percorso di alta formazione online in Data Analytics: Excel avanzato, SQL, Python, business intelligence e AI generativa in azienda. 30 CFU, 750 ore.",
               h1="Data Analytics <span class=\"grad\">per il Business</span>",
               lead="Un percorso pratico per trasformare i dati aziendali in decisioni: dalla raccolta alla visualizzazione, fino ai modelli predittivi e all'AI generativa nei processi.",
               credits=30, hours=750, level="Corso di alta formazione"),
    "m6": dict(url="/master-universitari/management-sanitario/", hub="master",
               name="Management Sanitario", short="Master Management Sanitario",
               title="Master in Management Sanitario online (I livello) | UNICESD Olympo",
               desc="Master universitario di I livello online in Management Sanitario: organizzazione dei servizi, programmazione, risk management e leadership. 60 CFU.",
               h1="Master in <span class=\"grad\">Management Sanitario</span>",
               lead="Per professionisti sanitari e amministrativi che assumono responsabilità organizzative in strutture pubbliche e private: servizi, economia sanitaria, rischio clinico e gestione dei team.",
               credits=60, hours=1500, level="Master universitario di I livello"),
    # --- certificazioni ---
    "k1": dict(url="/certificazioni/informatiche/", hub="certificazioni",
               name="Certificazioni Informatiche", short="Certificazioni informatiche",
               title="Certificazioni informatiche per concorsi e graduatorie | UNICESD",
               desc="Certificazioni informatiche online spendibili nei concorsi pubblici, nelle graduatorie scolastiche e nel lavoro: office, sicurezza, web e coding.",
               h1="Certificazioni <span class=\"grad\">informatiche</span>",
               lead="Formazione e certificazione delle competenze digitali, dall'alfabetizzazione al coding, spendibili nei concorsi pubblici, nelle graduatorie della scuola e nel mercato del lavoro.",
               level="Certificazione delle competenze digitali"),
    "k2": dict(url="/certificazioni/linguistiche/", hub="certificazioni",
               name="Certificazioni Linguistiche", short="Certificazioni linguistiche",
               title="Certificazioni linguistiche B1, B2, C1, C2 (QCER) | UNICESD Olympo",
               desc="Certificazioni linguistiche dal B1 al C2 secondo il Quadro Comune Europeo: inglese, francese, spagnolo, tedesco e italiano L2. Preparazione ed esame.",
               h1="Certificazioni linguistiche <span class=\"grad\">dal B1 al C2</span>",
               lead="Preparazione ed esame per certificare le competenze linguistiche secondo il Quadro Comune Europeo di Riferimento, in inglese, francese, spagnolo, tedesco e italiano L2.",
               level="Certificazione linguistica QCER"),
    "k3": dict(url="/certificazioni/graduatorie-scuola/", hub="certificazioni",
               name="Percorsi per Graduatorie", short="Punteggio graduatorie",
               title="Corsi per il punteggio nelle graduatorie scuola | UNICESD Olympo",
               desc="Corsi di perfezionamento, master e certificazioni per aumentare il punteggio nelle graduatorie del comparto scuola, con assistenza alla domanda.",
               h1="Percorsi per il punteggio <span class=\"grad\">nelle graduatorie</span>",
               lead="Un pacchetto di corsi, master e certificazioni pensato per chi partecipa all'aggiornamento delle graduatorie del comparto scuola, con assistenza nella compilazione della domanda.",
               level="Percorso per graduatorie scolastiche"),
    # --- corsi singoli e servizi ---
    "s1": dict(url="/corsi-singoli-cfu/", hub="singoli",
               name="Corsi Singoli e CFU", short="Corsi singoli",
               title="Corsi singoli universitari online per recuperare CFU | UNICESD",
               desc="Corsi singoli universitari online per acquisire i CFU mancanti per concorsi, classi di concorso o lauree magistrali, senza iscriverti a un intero corso.",
               h1="Corsi singoli online <span class=\"grad\">per i CFU che ti mancano</span>",
               lead="Se ti mancano alcuni crediti per un concorso, una classe di concorso o una laurea magistrale, puoi sostenere solo gli insegnamenti che ti servono, con costi proporzionali.",
               level="Corso singolo universitario"),
    "s2": dict(url="/riconoscimento-cfu/", hub="singoli",
               name="Riconoscimento della Carriera", short="Riconoscimento CFU",
               title="Riconoscimento CFU gratuito in 48 ore | UNICESD Olympo",
               desc="Valutazione gratuita dei crediti già maturati in università o nel lavoro: risposta in 48 ore e stima di quanto si accorcia il tuo percorso di laurea.",
               h1="Riconoscimento CFU <span class=\"grad\">gratuito</span>",
               lead="Analizziamo senza costi il tuo percorso di studi e la tua esperienza professionale per stimare quanti crediti possono essere riconosciuti e quanto si accorcia il percorso.",
               level="Servizio di valutazione della carriera"),
    "s3": dict(url="/formazione-aziendale/", hub="singoli",
               name="Formazione Aziendale", short="Formazione aziendale",
               title="Formazione aziendale su misura e finanziata | UNICESD Olympo",
               desc="Percorsi di formazione su misura per imprese, studi ed enti, anche blended e finanziabili con i fondi interprofessionali: export, digitale, AI, soft skill.",
               h1="Formazione aziendale <span class=\"grad\">su misura</span>",
               lead="Progettiamo percorsi per imprese, studi professionali ed enti, anche in modalità blended e finanziabili con i fondi interprofessionali o con il Fondo Nuove Competenze.",
               level="Formazione per le imprese"),
}

HUBS = {
    "lauree": dict(url="/corsi-di-laurea/", name="Corsi di laurea",
                   title="Corsi di laurea online triennali e magistrali | UNICESD Olympo",
                   desc="Lauree online triennali, magistrali e a ciclo unico: Giurisprudenza, Economia, Psicologia, Educazione, Ingegneria Informatica, Scienze Motorie.",
                   h1="Corsi di laurea <span class=\"grad\">online</span>",
                   eyebrow="Offerta formativa",
                   lead="Lauree triennali, magistrali e a ciclo unico con atenei partner: lezioni online sempre disponibili, esami nelle sedi convenzionate, un tutor dedicato dall'iscrizione alla laurea e la valutazione gratuita dei crediti che hai già.",
                   keys=["c1", "c2", "c3", "c4", "c5", "c6"], extra=["perche"]),
    "master": dict(url="/master-universitari/", name="Master universitari",
                   title="Master universitari online di I e II livello | UNICESD Olympo",
                   desc="Master universitari online di I e II livello e alta formazione: export e Made in Italy, turismo, didattica digitale, diritto internazionale, sanità.",
                   h1="Master universitari <span class=\"grad\">di I e II livello</span>",
                   eyebrow="Post laurea",
                   lead="Master executive, di I e II livello e corsi di alta formazione per chi lavora e vuole specializzarsi: 60 CFU e 1500 ore per i master, lezioni online e un tutor che ti segue fino al titolo.",
                   keys=["m1", "m2", "m3", "m4", "m5", "m6"], extra=["master", "perche"]),
    "certificazioni": dict(url="/certificazioni/", name="Certificazioni",
                   title="Certificazioni informatiche e linguistiche online | UNICESD Olympo",
                   desc="Certificazioni informatiche e linguistiche (B1-C2) e percorsi per il punteggio nelle graduatorie scuola e nei concorsi pubblici. Orientamento gratuito.",
                   h1="Certificazioni <span class=\"grad\">informatiche e linguistiche</span>",
                   eyebrow="Competenze certificate",
                   lead="Titoli valutabili per concorsi pubblici, graduatorie della scuola e curriculum: competenze digitali, lingue straniere dal B1 al C2 e pacchetti pensati per il punteggio.",
                   keys=["k1", "k2", "k3"], extra=["perche"]),
}

# ---------------------------------------------------------------------------
# Pagine tematiche: riusano le sezioni della home
# ---------------------------------------------------------------------------
PAGES = [
    dict(url="/offerta-formativa/", name="Offerta formativa",
         title="Offerta formativa: lauree, master e certificazioni | UNICESD",
         desc="Tutta l'offerta UNICESD Olympo: corsi di laurea online, master di I e II livello, certificazioni informatiche e linguistiche, corsi singoli e CFU.",
         h1="Offerta formativa <span class=\"grad\">UNICESD Olympo</span>",
         eyebrow="Lauree · Master · Certificazioni",
         lead="Corsi di laurea, master universitari, certificazioni e corsi singoli attivati con atenei e reti formative accreditate. Studi online, sostieni gli esami in sede e hai sempre un tutor di riferimento.",
         sections=["offerta", "master", "perche"], hubs=True),
    dict(url="/janus-diploma-online/", name="Janus, diploma online",
         title="Diploma online con Janus: 11 indirizzi e tutor | UNICESD Olympo",
         desc="Janus – Istituto Superiore per la Formazione: scuola online per il diploma con 11 indirizzi fra licei, tecnici e professionali, tutor personale e sede a Roma.",
         h1="Diploma online con <span class=\"grad\">Janus</span>",
         eyebrow="Istituto Superiore per la Formazione",
         lead="La scuola online del diploma nella rete UNICESD Olympo: undici indirizzi fra licei, istituti tecnici e professionali, piattaforma attiva 24 ore su 24, un tutor personale per ogni studente e una sede vera a Roma.",
         sections=["janus"]),
    dict(url="/medicina-senza-test-ingresso/", name="Medicina senza test d'ingresso",
         title="Medicina senza test d'ingresso in Europa | UNICESD Olympo",
         desc="Studiare Medicina, Odontoiatria, Infermieristica, Igiene Dentale e Fisioterapia in università europee senza test d'ingresso. Dall'iscrizione al riconoscimento.",
         h1="Medicina e area sanitaria <span class=\"grad\">senza test d'ingresso</span>",
         eyebrow="Studiare all'estero",
         lead="Medicina, Odontoiatria, Igiene Dentale, Infermieristica e Fisioterapia in università europee riconosciute, con ammissione senza test o programmata. Con Study with Athena seguiamo lo studente dalla scelta dell'ateneo al rientro in Italia.",
         sections=["athena"]),
    dict(url="/intelligenza-artificiale-ai-act/", name="Formazione AI e AI Act",
         title="Corsi AI Act e formazione sull'intelligenza artificiale | UNICESD",
         desc="Formazione sull'intelligenza artificiale e sul Regolamento UE AI Act per imprese, PA e professionisti: AI literacy, governance, compliance e consulenza.",
         h1="Formazione su intelligenza artificiale <span class=\"grad\">e AI Act</span>",
         eyebrow="Progetto Intelligenza Artificiale",
         lead="Percorsi a livelli, costruiti con Studio Eremita, per usare l'intelligenza artificiale in modo consapevole e conforme al regolamento europeo: dall'alfabetizzazione alla governance interna, fino al percorso da consulente.",
         sections=["ai"]),
    dict(url="/fondo-nuove-competenze-2026/", name="Fondo Nuove Competenze 2026",
         title="Fondo Nuove Competenze 2026: formazione finanziata | UNICESD",
         desc="Fondo Nuove Competenze 2026: lo Stato rimborsa alle imprese il costo del personale in formazione. Durata, linee di finanziamento, iter e certificazione.",
         h1="Fondo Nuove Competenze <span class=\"grad\">2026</span>",
         eyebrow="Per le imprese",
         lead="La misura nazionale che rimborsa alle aziende la retribuzione delle ore dedicate alla formazione. Ti aiutiamo a progettare il percorso, dalla domanda alla rendicontazione, con certificazione delle competenze e CFU.",
         sections=["fnc"]),
    dict(url="/chi-siamo/", name="Chi siamo",
         title="Chi siamo: il Centro Studi di Palermo dal 2015 | UNICESD Olympo",
         desc="Universitas Centro Studi Olympo, Palermo: storia dal 2008, dati societari, il Gruppo Olympo CDC e la rassegna stampa. Orientamento e tutoraggio universitario.",
         h1="Chi siamo: <span class=\"grad\">Universitas Centro Studi Olympo</span>",
         eyebrow="Il Centro Studi",
         lead="UNICESD Olympo nasce a Palermo nel 2015, in continuazione di Helios e Icarus attive dal 2008: costruiamo il ponte tra chi vuole studiare e gli atenei che rilasciano il titolo, con orientamento, tutoraggio e coordinamento didattico.",
         sections=["ateneo", "storia", "gruppo", "stampa"], org_full=True),
    dict(url="/calogero-di-carlo/", name="Calogero Di Carlo",
         title="Calogero Di Carlo, fondatore di UNICESD Olympo | Biografia",
         desc="Calogero Di Carlo: da ufficiale di PG a direttore delle sedi nazionali dell'Università Pegaso, fino a UNICESD Olympo. Biografia, interventi e riconoscimenti.",
         h1="Calogero Di Carlo, <span class=\"grad\">il fondatore</span>",
         eyebrow="Biografia",
         lead="Ufficiale di PG, coordinatore del progetto che ha portato alla laurea circa ventimila marescialli, direttore di 100 sedi d'esame dell'Università Telematica Pegaso e fondatore, nel 2015, di UNICESD Olympo.",
         sections=["fondatore", "voce"], person=True, og="/assets/founder-cers.webp"),
    dict(url="/eventi/", name="Eventi",
         title="Eventi, convention e open day | UNICESD Olympo",
         desc="L'agenda di UNICESD Olympo e di Calogero Di Carlo: la Convention del 18 settembre 2026 a Roma, open day, incontri istituzionali e la galleria fotografica.",
         h1="Eventi <span class=\"grad\">UNICESD Olympo</span>",
         eyebrow="Agenda",
         lead="Convention, open day, incontri istituzionali e appuntamenti sportivi della rete, con il programma e le fotografie della Convention del 18 settembre 2026 al TH Roma Carpegna Palace.",
         sections=["eventi", "programma-sec", "icameback"], event=True, og="/assets/eventi/icb/icb-06.webp"),
    dict(url="/servizi-studenti/", name="Servizi agli studenti",
         title="Servizi agli studenti e piattaforma e-learning | UNICESD Olympo",
         desc="Tutor dedicato, piattaforma e-learning 24/7, valutazione CFU in 48 ore, segreteria didattica, DSA e BES, tirocini e rate personalizzate.",
         h1="Servizi agli studenti e <span class=\"grad\">piattaforma e-learning</span>",
         eyebrow="Studenti",
         lead="Dalla prima informazione alla proclamazione: orientamento gratuito, un tutor unico, una piattaforma sempre aperta, la segreteria didattica e i servizi per DSA e BES.",
         sections=["servizi", "piattaforma", "perche"]),
    dict(url="/rete-e-partner/", name="Rete e partner",
         title="Rete e partner: atenei, enti e imprese | UNICESD Olympo",
         desc="La rete di UNICESD Olympo: atenei e istituti, certificazioni e lingue, area sanitaria internazionale, sport, editoria, innovazione e rappresentanza d'impresa.",
         h1="La rete e i <span class=\"grad\">partner</span>",
         eyebrow="Rete e partnership",
         lead="Atenei, istituti, associazioni di categoria, testate e realtà sportive: le organizzazioni che lavorano con UNICESD Olympo e quelle in cui il fondatore ricopre un ruolo.",
         sections=["partner"]),
    dict(url="/sedi/", name="Sedi",
         title="Sedi UNICESD Olympo: Palermo, Cefalù e Lisbona",
         desc="Sede legale in Via Trabia 1 e sede operativa in Largo Lituania 11 a Palermo, presidio a Cefalù e filiale di Lisbona. Indirizzi, telefoni e sedi d'esame.",
         h1="Le sedi: <span class=\"grad\">Palermo, Cefalù e Lisbona</span>",
         eyebrow="Dove siamo",
         lead="Da Palermo coordiniamo i poli didattici e le sedi d'esame convenzionate in tutta Italia; a Lisbona opera la filiale portoghese. Qui trovi indirizzi, recapiti e orari.",
         sections=["sedi"], org_full=True, local=True),
    dict(url="/apri-una-sede/", name="Apri una sede",
         title="Apri una sede E-Learning Center Point | UNICESD Olympo",
         desc="Diventa E-Learning Center Point UNICESD Olympo: requisiti minimi dei locali per sede formativa e di orientamento, condizioni e modulo di candidatura.",
         h1="Apri una sede <span class=\"grad\">E-Learning Center Point</span>",
         eyebrow="Affiliazione",
         lead="Hai una struttura idonea e vuoi diventare il punto di riferimento formativo del tuo territorio? Ecco i requisiti dei locali, le condizioni e come candidarti alla rete ECP Olympo.",
         sections=["apri-sede"]),
    dict(url="/faq/", name="Domande frequenti",
         title="Domande frequenti su lauree, CFU ed esami | UNICESD Olympo",
         desc="Chi rilascia il titolo, come si studia lavorando, come funziona il riconoscimento CFU, costi e rate, dove si fanno gli esami: le risposte di UNICESD Olympo.",
         h1="Domande <span class=\"grad\">frequenti</span>",
         eyebrow="FAQ",
         lead="Le domande che ci fanno più spesso prima dell'iscrizione. Se la tua non c'è, lascia i recapiti in fondo alla pagina: ti richiamiamo entro 24 ore lavorative.",
         sections=["faq"], faq=True),
    dict(url="/contatti/", name="Contatti",
         title="Contatti e orientamento gratuito | UNICESD Olympo Palermo",
         desc="Contatta UNICESD Olympo: telefoni della segreteria, sede di Palermo in Via Trabia 1 e modulo per un colloquio di orientamento gratuito entro 24 ore.",
         h1="Contatti e <span class=\"grad\">orientamento gratuito</span>",
         eyebrow="Contatti",
         lead="Lascia nome e recapito: un orientatore ti chiama entro 24 ore lavorative per un colloquio gratuito e senza impegno. Oppure chiamaci subito.",
         sections=[], org_full=True, local=True, contact=True),
]

# ---------------------------------------------------------------------------
# Ancore della home -> pagine dedicate (usate in header, menu mobile, footer)
# ---------------------------------------------------------------------------
ANCHOR_MAP = {
    "top": "/",
    "ateneo": "/chi-siamo/",
    "gruppo": "/chi-siamo/#gruppo",
    "storia": "/chi-siamo/#storia",
    "stampa": "/chi-siamo/#stampa",
    "fondatore": "/calogero-di-carlo/",
    "voce": "/calogero-di-carlo/#voce",
    "partner": "/rete-e-partner/",
    "janus": "/janus-diploma-online/",
    "janus-corsi": "/janus-diploma-online/#janus-corsi",
    "eventi": "/eventi/",
    "icameback": "/eventi/#icameback",
    "programma": "/eventi/#programma",
    "programma-sec": "/eventi/#programma-sec",
    "master": "/master-made-in-italy-global-leadership/",
    "ai": "/intelligenza-artificiale-ai-act/",
    "fnc": "/fondo-nuove-competenze-2026/",
    "offerta": "/offerta-formativa/",
    "athena": "/medicina-senza-test-ingresso/",
    "servizi": "/servizi-studenti/",
    "piattaforma": "/servizi-studenti/#piattaforma",
    "perche": "/servizi-studenti/#perche",
    "sedi": "/sedi/",
    "apri-sede": "/apri-una-sede/",
    "faq": "/faq/",
    "contatti": "/contatti/",
    "iscrizione": "/contatti/",
}
# voci del mega-menu con data-tab: vanno all'hub giusto
TAB_MAP = {"0": "/corsi-di-laurea/", "1": "/master-universitari/", "2": "/certificazioni/"}
# link che puntano a #offerta / #servizi ma parlano di una voce precisa: si sceglie dal testo
TEXT_MAP = [
    ("corsi singoli", "/corsi-singoli-cfu/"),
    ("riconoscimento cfu", "/riconoscimento-cfu/"),
    ("corsi di laurea", "/corsi-di-laurea/"),
    ("triennali", "/corsi-di-laurea/"),
    ("magistrali", "/corsi-di-laurea/"),
    ("ciclo unico", "/corsi-di-laurea/giurisprudenza/"),
    ("master", "/master-universitari/"),
    ("alta formazione", "/master-universitari/"),
    ("certificazioni", "/certificazioni/"),
    ("informatiche", "/certificazioni/informatiche/"),
    ("linguistiche", "/certificazioni/linguistiche/"),
    ("concorsi e graduatorie", "/certificazioni/graduatorie-scuola/"),
    ("piattaforma", "/servizi-studenti/#piattaforma"),
]
