# -*- coding: utf-8 -*-
"""
Pagine aggiunte il 10 ottobre 2026: gli 11 indirizzi del diploma online (Janus),
il recupero degli anni scolastici e i percorsi sanitari all'estero (Study with Athena).

Formato dei blocchi (lo legge build_extra.py):
  (titolo H2, [contenuto, ...]) dove ogni contenuto e':
    "testo html"                -> paragrafo
    ("ul", [voci])              -> elenco con spunta
    ("ol", [voci])              -> elenco numerato a passi
    ("table", [intestazioni], [[celle], ...])
"""

JANUS_HUB = ("/janus-diploma-online/", "Diploma online")

# blocco comune, scritto in 3 varianti per non ripetere lo stesso testo su 11 pagine
COME = [
    ["Studi sulla piattaforma <b>LMS Innova</b>, attiva 24 ore su 24, con oltre 15.000 ore di lezioni, mappe concettuali e dispense in pdf.",
     "Un <b>tutor personale</b> costruisce con te il piano di studio e controlla il ritmo, anche se lavori o devi recuperare più anni.",
     "Al quinto anno c'è la <b>Janus Academy</b>: 9 ore di lezioni live a settimana, la sera dopo le 18, sempre registrate."],
    ["Le lezioni sono sempre disponibili, da computer, tablet o telefono, e ogni argomento ha la sua mappa e il suo pdf.",
     "Il tutor virtuale risponde in tempo reale e le <b>interrogazioni simulate</b> ti dicono a che punto sei prima dell'esame.",
     "Il tutor umano ti segue dall'iscrizione all'esame e ti aiuta a scegliere quando e dove sostenerlo."],
    ["Nessun orario fisso: studi quando puoi, con un piano costruito sulle tue giornate.",
     "Laboratori live e <b>speaking areas</b> per esercitarti con docenti e compagni.",
     "Per la maturità, la preparazione serale della Janus Academy, con lezioni registrate per chi lavora."],
]

DIPLOMI = [
    dict(slug="liceo-scientifico", tipo="Liceo", nome="Liceo Scientifico",
         title="Diploma di Liceo Scientifico online | UNICESD Olympo",
         desc="Diploma di liceo scientifico online con tutor personale: recupero anni, esami di idoneità e maturità. Matematica, fisica e scienze sempre in piattaforma.",
         h1="Diploma di <span class=\"grad\">Liceo Scientifico</span> online",
         lead="Matematica, fisica, scienze, latino e filosofia studiati online, con un tutor personale che ti porta fino alla maturità o all'esame di idoneità.",
         per="per chi punta a facoltà scientifiche, ingegneria, medicina o economia",
         materie=["Lingua e letteratura italiana", "Lingua e cultura latina", "Lingua e cultura inglese", "Storia e filosofia", "Matematica (con informatica al primo biennio)", "Fisica", "Scienze naturali (biologia, chimica, scienze della Terra)", "Disegno e storia dell'arte", "Scienze motorie"],
         intro="Il liceo scientifico è l'indirizzo più scelto dagli studenti italiani perché tiene aperte tutte le porte: unisce una solida preparazione matematica e scientifica a una formazione umanistica completa, con latino e filosofia. Studiarlo online significa poter seguire matematica e fisica al proprio ritmo, rivedendo le lezioni tutte le volte che serve.",
         dopo=["Ingegneria, matematica, fisica e informatica", "Medicina, odontoiatria e professioni sanitarie (anche <a href=\"/medicina-senza-test-ingresso/\">all'estero senza test</a>)", "Economia, architettura e scienze", "Qualsiasi altro corso universitario"],
         faq=[("Il liceo scientifico online è più difficile?", "Il programma è lo stesso del liceo in presenza. La differenza è che lo studi con i tuoi tempi, con lezioni registrate e un tutor che ti aiuta sulle materie più impegnative come matematica e fisica."),
              ("Posso passare dallo scientifico alle scienze applicate?", "Sì, si può cambiare indirizzo con esami integrativi sulle materie che non hai studiato. Il tutor ti indica quali.")]),
    dict(slug="liceo-scientifico-sportivo", tipo="Liceo", nome="Liceo Scientifico a indirizzo Sportivo",
         title="Liceo Scientifico Sportivo online: diploma per atleti | UNICESD",
         desc="Diploma di liceo scientifico sportivo online, pensato per chi si allena e gareggia: lezioni sempre disponibili, tutor personale ed esami di idoneità.",
         h1="Liceo Scientifico <span class=\"grad\">Sportivo</span> online",
         lead="Il liceo per chi vive di sport: allenamenti e trasferte non sono più un problema, perché le lezioni ti aspettano in piattaforma.",
         per="per atleti agonisti e per chi vuole lavorare nel mondo dello sport",
         materie=["Lingua e letteratura italiana", "Lingua e cultura inglese", "Storia e filosofia", "Matematica e fisica", "Scienze naturali", "Diritto ed economia dello sport", "Scienze motorie e sportive", "Discipline sportive"],
         intro="Il liceo scientifico a indirizzo sportivo unisce le materie del liceo scientifico, senza latino, allo studio scientifico dello sport: fisiologia del movimento, diritto ed economia dello sport, discipline sportive. Online è la soluzione naturale per chi si allena ogni giorno e gareggia nei fine settimana.",
         dopo=["<a href=\"/corsi-di-laurea/scienze-motorie/\">Scienze motorie L-22</a> e poi la <a href=\"/corsi-di-laurea/magistrale-scienze-motorie/\">magistrale LM-67</a>", "Fisioterapia e professioni sanitarie", "Management dello sport ed economia", "Qualsiasi altro corso universitario"],
         faq=[("Sono un atleta e sono spesso in trasferta: come faccio?", "Le lezioni sono sempre disponibili e le studi dove sei. Il tutor organizza il piano di studio sul tuo calendario di gare."),
              ("È un liceo vero o un corso sportivo?", "È un indirizzo del liceo scientifico, con diploma di liceo valido per l'accesso a qualsiasi università.")]),
    dict(slug="liceo-scienze-applicate", tipo="Liceo", nome="Liceo Scientifico opzione Scienze Applicate",
         title="Liceo Scienze Applicate online: diploma senza latino | UNICESD",
         desc="Diploma di liceo scientifico opzione scienze applicate online: più informatica e laboratorio, niente latino. Recupero anni, idoneità e maturità con tutor.",
         h1="Liceo <span class=\"grad\">Scienze Applicate</span> online",
         lead="Il liceo scientifico senza latino, con più informatica, chimica e biologia: online, con un tutor e lezioni sempre disponibili.",
         per="per chi ama le materie scientifiche e l'informatica",
         materie=["Lingua e letteratura italiana", "Lingua e cultura inglese", "Storia e filosofia", "Matematica", "Informatica", "Fisica", "Scienze naturali (con più ore di chimica e biologia)", "Disegno e storia dell'arte", "Scienze motorie"],
         intro="L'opzione scienze applicate sostituisce il latino con l'informatica e rafforza le scienze sperimentali. È il liceo scelto da chi si sente portato per i numeri, la programmazione e il metodo scientifico, e vuole una preparazione concreta in vista di facoltà tecniche e scientifiche.",
         dopo=["<a href=\"/corsi-di-laurea/ingegneria-informatica/\">Ingegneria informatica</a> e le altre ingegnerie", "<a href=\"/corsi-di-laurea/scienze-biologiche/\">Scienze biologiche</a>, chimica, biotecnologie", "Professioni sanitarie", "Informatica e data science"],
         faq=[("Che differenza c'è con lo scientifico tradizionale?", "Niente latino, più informatica e più ore di scienze. Il diploma è sempre di liceo scientifico."),
              ("I laboratori come si fanno online?", "Con simulazioni, video e attività guidate in piattaforma, più i laboratori live con i docenti.")]),
    dict(slug="liceo-classico", tipo="Liceo", nome="Liceo Classico",
         title="Diploma di Liceo Classico online con tutor | UNICESD Olympo",
         desc="Diploma di liceo classico online: latino, greco, letteratura e filosofia con lezioni sempre disponibili, tutor personale, idoneità e maturità.",
         h1="Diploma di <span class=\"grad\">Liceo Classico</span> online",
         lead="Latino, greco, letteratura e filosofia con i tuoi tempi: il liceo della tradizione, studiato online con un tutor accanto.",
         per="per chi ama le materie umanistiche e punta a giurisprudenza, lettere o filosofia",
         materie=["Lingua e letteratura italiana", "Lingua e cultura latina", "Lingua e cultura greca", "Lingua e cultura inglese", "Storia e geografia (primo biennio)", "Storia e filosofia", "Matematica e fisica", "Scienze naturali", "Storia dell'arte"],
         intro="Il liceo classico allena come nessun altro la capacità di analizzare, argomentare e tradurre: è il motivo per cui resta il liceo di riferimento per chi punta a giurisprudenza, lettere, filosofia e, sempre più spesso, anche a medicina. Online puoi dedicare a latino e greco il tempo che chiedono, con le versioni guidate e il supporto del tutor.",
         dopo=["<a href=\"/corsi-di-laurea/giurisprudenza/\">Giurisprudenza</a>", "<a href=\"/corsi-di-laurea/lettere/\">Lettere</a> e filosofia", "Scienze politiche e relazioni internazionali", "Medicina e tutte le altre facoltà"],
         faq=[("Si può recuperare un anno di classico online?", "Sì, con l'esame di idoneità. Il tutor ti prepara in particolare su latino e greco, che sono le materie su cui si concentra la prova."),
              ("Le versioni di latino e greco come si preparano?", "Con lezioni di grammatica, esercizi guidati e correzioni, oltre ai laboratori live con i docenti.")]),
    dict(slug="liceo-linguistico", tipo="Liceo", nome="Liceo Linguistico",
         title="Diploma di Liceo Linguistico online | UNICESD Olympo",
         desc="Diploma di liceo linguistico online: tre lingue straniere fino al livello B2, speaking areas e voce artificiale per la pronuncia. Tutor personale.",
         h1="Diploma di <span class=\"grad\">Liceo Linguistico</span> online",
         lead="Tre lingue straniere, letterature e culture europee: online, con speaking areas per parlare e una voce artificiale che ti aiuta con la pronuncia.",
         per="per chi vuole lavorare con le lingue, nel turismo o all'estero",
         materie=["Lingua e letteratura italiana", "Lingua latina (primo biennio)", "Lingua e cultura straniera 1, 2 e 3", "Storia e geografia, storia e filosofia", "Matematica e fisica", "Scienze naturali", "Storia dell'arte", "Scienze motorie"],
         intro="Il liceo linguistico porta a un livello B2 in due lingue europee e B1 in una terza, con lo studio delle loro letterature e culture. Online funziona particolarmente bene: la piattaforma traduce i contenuti in più lingue, legge i testi ad alta voce e le speaking areas permettono di esercitarsi a parlare con docenti e compagni.",
         dopo=["<a href=\"/corsi-di-laurea/lingue-culture/\">Lingue e culture L-11</a>", "Mediazione linguistica, traduzione e interpretariato", "<a href=\"/corsi-di-laurea/scienze-turismo/\">Scienze del turismo</a>", "Relazioni internazionali e comunicazione"],
         faq=[("Si può parlare con un docente madrelingua?", "Nelle speaking areas e nei laboratori live ti eserciti nella conversazione con docenti e compagni."),
              ("Posso prendere anche una certificazione linguistica?", "Sì, ed è una buona idea: possiamo prepararti anche alle <a href=\"/certificazioni/linguistiche/\">certificazioni dal B1 al C2</a>.")]),
    dict(slug="liceo-scienze-umane", tipo="Liceo", nome="Liceo delle Scienze Umane",
         title="Diploma di Liceo delle Scienze Umane online | UNICESD Olympo",
         desc="Diploma di liceo delle scienze umane online: pedagogia, psicologia, sociologia e antropologia. Recupero anni, idoneità e maturità con tutor personale.",
         h1="Diploma di Liceo delle <span class=\"grad\">Scienze Umane</span> online",
         lead="Pedagogia, psicologia, sociologia e antropologia: il liceo per chi vuole lavorare con le persone, studiato online con un tutor personale.",
         per="per chi pensa all'educazione, alla psicologia o al sociale",
         materie=["Lingua e letteratura italiana", "Lingua e cultura latina", "Lingua e cultura inglese", "Scienze umane (pedagogia, psicologia, antropologia, sociologia)", "Storia e filosofia", "Diritto ed economia (primo biennio)", "Matematica e fisica", "Scienze naturali", "Storia dell'arte"],
         intro="Il liceo delle scienze umane studia i fenomeni educativi, relazionali e sociali: come si impara, come crescono i bambini, come funzionano i gruppi e le comunità. È il liceo che prepara meglio a chi pensa di diventare educatore, insegnante, psicologo o assistente sociale.",
         dopo=["<a href=\"/corsi-di-laurea/scienze-educazione/\">Scienze dell'educazione L-19</a>", "<a href=\"/corsi-di-laurea/scienze-psicologiche/\">Scienze psicologiche L-24</a>", "Scienze della formazione primaria e servizio sociale", "Sociologia e scienze politiche"],
         faq=[("Che differenza c'è con l'economico sociale?", "Le scienze umane hanno il latino e più pedagogia e psicologia; l'economico sociale ha diritto ed economia e una seconda lingua straniera al posto del latino."),
              ("È adatto a chi lavora già nel sociale?", "Sì, molti iscritti lavorano come assistenti o operatori e vogliono il diploma per proseguire all'università.")]),
    dict(slug="liceo-economico-sociale", tipo="Liceo", nome="Liceo delle Scienze Umane opzione Economico-Sociale",
         title="Liceo Economico Sociale (LES) online: diploma con tutor | UNICESD",
         desc="Diploma di liceo economico sociale online: diritto, economia, scienze umane e due lingue straniere. Lezioni sempre disponibili e tutor personale.",
         h1="Liceo <span class=\"grad\">Economico Sociale</span> online",
         lead="Diritto, economia, sociologia e due lingue straniere: il liceo per capire come funzionano mercati e società, studiato online.",
         per="per chi è interessato a economia, diritto e società",
         materie=["Lingua e letteratura italiana", "Lingua e cultura straniera 1 e 2", "Diritto ed economia politica", "Scienze umane (antropologia, metodologia della ricerca, psicologia, sociologia)", "Storia e filosofia", "Matematica e fisica", "Scienze naturali", "Storia dell'arte"],
         intro="L'opzione economico-sociale del liceo delle scienze umane (LES) mette al centro diritto ed economia, insieme a sociologia e statistica: è il liceo per chi vuole capire il lavoro, i mercati e le istituzioni, senza il latino e con due lingue straniere.",
         dopo=["<a href=\"/corsi-di-laurea/economia-aziendale/\">Economia</a> e <a href=\"/corsi-di-laurea/scienze-politiche/\">Scienze politiche</a>", "<a href=\"/corsi-di-laurea/servizi-giuridici/\">Servizi giuridici</a> e Giurisprudenza", "Sociologia e scienze sociali", "Comunicazione e marketing"],
         faq=[("Il LES è un liceo o un istituto tecnico?", "È un liceo: l'opzione economico-sociale del liceo delle scienze umane."),
              ("Con il LES posso iscrivermi a Giurisprudenza?", "Sì, come con qualsiasi diploma quinquennale; diritto ed economia ti danno anzi una buona base di partenza.")]),
    dict(slug="tecnico-informatico", tipo="Istituto tecnico", nome="Istituto Tecnico Tecnologico Informatica e Telecomunicazioni",
         title="Diploma di Perito Informatico online | UNICESD Olympo",
         desc="Diploma tecnico informatico online (Informatica e Telecomunicazioni): programmazione, reti, sistemi e basi di dati. Recupero anni e maturità con tutor.",
         h1="Diploma di <span class=\"grad\">Perito Informatico</span> online",
         lead="Programmazione, reti, sistemi e basi di dati: il diploma tecnico per lavorare nell'informatica, studiato online con un tutor.",
         per="per chi vuole lavorare nell'IT o proseguire in ingegneria informatica",
         materie=["Lingua e letteratura italiana e storia", "Lingua inglese", "Matematica", "Informatica", "Sistemi e reti", "Tecnologie e progettazione di sistemi informatici e di telecomunicazioni", "Telecomunicazioni", "Gestione progetto e organizzazione d'impresa"],
         intro="L'istituto tecnico tecnologico a indirizzo Informatica e Telecomunicazioni forma tecnici capaci di analizzare, progettare, installare e gestire sistemi informatici, reti e basi di dati. È un diploma che si spende subito nel mondo del lavoro e che prepara bene a ingegneria e informatica.",
         dopo=["<a href=\"/corsi-di-laurea/ingegneria-informatica/\">Ingegneria informatica L-8</a>", "Informatica e data science", "ITS Academy in ambito digitale", "Lavoro come tecnico IT, sistemista o sviluppatore"],
         faq=[("Posso diplomarmi in informatica se lavoro già nel settore?", "Sì, è il caso di molti iscritti: tecnici e sviluppatori senza diploma che vogliono il titolo per crescere o proseguire all'università."),
              ("Le materie tecniche si possono studiare online?", "Sono tra le più adatte: programmazione e reti si imparano facendo, con esercizi e progetti in piattaforma.")]),
    dict(slug="ragioneria-afm", tipo="Istituto tecnico", nome="Amministrazione, Finanza e Marketing (ex Ragioneria)",
         title="Diploma di Ragioneria online (AFM) | UNICESD Olympo",
         desc="Diploma di ragioneria online, indirizzo Amministrazione Finanza e Marketing: economia aziendale, diritto e lingue. L'indirizzo più scelto, con tutor personale.",
         h1="Diploma di <span class=\"grad\">Ragioneria</span> online (AFM)",
         lead="Amministrazione, Finanza e Marketing, la vecchia ragioneria: l'indirizzo più scelto dai nostri studenti, con il 22,89% delle iscrizioni.",
         per="per chi lavora in ufficio o vuole fare il ragioniere, il contabile o proseguire a economia",
         materie=["Lingua e letteratura italiana e storia", "Lingua inglese e seconda lingua comunitaria", "Matematica", "Economia aziendale", "Diritto", "Economia politica", "Informatica", "Scienze integrate (primo biennio)"],
         intro="L'indirizzo Amministrazione, Finanza e Marketing è l'erede della ragioneria: bilancio, contabilità, fisco, marketing e diritto, con due lingue straniere. È il diploma più scelto da chi lavora in ufficio senza titolo, da chi gestisce un'attività di famiglia e da chi vuole proseguire con economia.",
         dopo=["<a href=\"/corsi-di-laurea/economia-aziendale/\">Economia aziendale</a> e le altre lauree economiche", "Consulenza del lavoro con <a href=\"/corsi-di-laurea/servizi-giuridici/\">Servizi giuridici L-14</a>", "Lavoro in amministrazione, contabilità, banche e assicurazioni", "Concorsi pubblici che richiedono il diploma"],
         faq=[("Il diploma AFM è lo stesso di ragioneria?", "Sì: dalla riforma dei tecnici del 2010 la ragioneria si chiama Amministrazione, Finanza e Marketing."),
              ("Posso recuperare due anni insieme?", "In molti casi sì, con l'esame di idoneità: il tutor valuta la tua situazione e costruisce un piano per recuperare gli anni nel minor tempo possibile.")]),
    dict(slug="socio-sanitario", tipo="Istituto professionale", nome="Servizi per la Sanità e l'Assistenza Sociale",
         title="Diploma Socio Sanitario online | UNICESD Olympo",
         desc="Diploma professionale socio sanitario online (Servizi per la sanità e l'assistenza sociale): igiene, psicologia e legislazione. Base per OSS e infermieristica.",
         h1="Diploma <span class=\"grad\">Socio Sanitario</span> online",
         lead="Il diploma professionale per chi lavora o vuole lavorare nell'assistenza, nella sanità e nel sociale, con un piano di studio costruito sui tuoi turni.",
         per="per OSS, assistenti, operatori del sociale e per chi punta a infermieristica",
         materie=["Lingua e letteratura italiana e storia", "Lingua inglese e seconda lingua", "Matematica", "Igiene e cultura medico-sanitaria", "Psicologia generale e applicata", "Diritto, economia e tecnica amministrativa del settore socio-sanitario", "Metodologie operative", "Scienze umane e sociali"],
         intro="L'istituto professionale Servizi per la sanità e l'assistenza sociale forma operatori capaci di riconoscere i bisogni socio-sanitari, collaborare a piani di intervento e lavorare nelle reti di servizi. È il diploma scelto da molti operatori che lavorano già in RSA, cooperative e assistenza domiciliare.",
         dopo=["Infermieristica e professioni sanitarie (anche <a href=\"/infermieristica-senza-test-ingresso/\">all'estero, con crediti per chi viene dal corso OSS</a>)", "<a href=\"/corsi-di-laurea/scienze-educazione/\">Scienze dell'educazione</a> e servizio sociale", "Corsi regionali di qualifica come OSS", "Lavoro in strutture sanitarie, socio-assistenziali e cooperative"],
         faq=[("Il diploma socio sanitario vale come qualifica OSS?", "No: l'OSS è una qualifica regionale con un suo corso. Il diploma però è un'ottima base e apre l'accesso all'università, per esempio a infermieristica."),
              ("Lavoro a turni in una RSA: riesco a studiare?", "Sì, le lezioni sono sempre disponibili e il tutor organizza il piano sugli orari che hai.")]),
    dict(slug="tecnico-turismo", tipo="Istituto tecnico", nome="Istituto Tecnico per il Turismo",
         title="Diploma Tecnico per il Turismo online | UNICESD Olympo",
         desc="Diploma di istituto tecnico per il turismo online: discipline turistiche, tre lingue, arte e territorio, marketing digitale. Tutor e lezioni sempre disponibili.",
         h1="Diploma <span class=\"grad\">Tecnico per il Turismo</span> online",
         lead="Discipline turistiche, tre lingue straniere, arte e territorio: il diploma per lavorare nell'accoglienza, studiato online anche durante la stagione.",
         per="per chi lavora nel turismo o vuole entrarci",
         materie=["Lingua e letteratura italiana e storia", "Lingua inglese, seconda e terza lingua straniera", "Matematica", "Discipline turistiche e aziendali", "Geografia turistica", "Diritto e legislazione turistica", "Arte e territorio", "Informatica"],
         intro="L'istituto tecnico per il turismo prepara a progettare e gestire servizi turistici, promuovere il patrimonio culturale e usare gli strumenti digitali di promozione. Online è particolarmente comodo per chi lavora in hotel, bar e agenzie durante la stagione e studia nei mesi di bassa.",
         dopo=["<a href=\"/corsi-di-laurea/scienze-turismo/\">Scienze del turismo L-15</a>", "<a href=\"/master-universitari/management-imprese-turistiche/\">Management delle imprese turistiche</a>, dopo la laurea", "Lingue e mediazione", "Lavoro in strutture ricettive, agenzie e tour operator"],
         faq=[("Lavoro d'estate: posso studiare solo d'inverno?", "Sì, il piano di studio si costruisce sui tuoi mesi liberi; d'estate puoi rallentare senza perdere il filo."),
              ("Quali lingue si studiano?", "Inglese più due lingue straniere: le combinazioni disponibili te le indica il tutor.")]),
]

RECUPERO = dict(
    url="/recupero-anni-scolastici/", name="Recupero anni scolastici",
    title="Recupero anni scolastici online: idoneità e maturità | UNICESD",
    desc="Recupera uno o più anni scolastici online con l'esame di idoneità e preparati alla maturità da privatista: tutor personale, 11 indirizzi, 98% promossi.",
    h1="Recupero <span class=\"grad\">anni scolastici</span> online",
    eyebrow="Diploma · Idoneità · Maturità",
    lead="Hai interrotto la scuola, sei stato bocciato o lavori e non hai il diploma? Con l'esame di idoneità puoi recuperare uno o più anni e arrivare alla maturità, studiando online con un tutor.",
    blocks=[
        ("Come funziona il recupero degli anni", [
            "In Italia si può sostenere da <b>candidato privatista</b> l'esame di idoneità per essere ammessi a una classe successiva a quella che si è frequentato, e poi l'esame di Stato (maturità). Questo permette, in molti casi, di <b>recuperare più anni in uno</b>, a condizione di rispettare i requisiti di età e i titoli previsti dalla normativa.",
            "La preparazione si fa online: il tutor personale verifica la tua situazione (ultimo anno superato, indirizzo, età), costruisce un piano di studio sulle materie dell'esame e ti segue fino alla prova, che si sostiene presso una scuola statale o paritaria.",
        ]),
        ("I passaggi, uno per uno", [
            ("ol", ["<b>Colloquio gratuito</b>: raccontaci da dove parti e dove vuoi arrivare.",
                    "<b>Analisi del percorso</b>: il tutor verifica anni e materie già superati e calcola quanti anni puoi recuperare.",
                    "<b>Piano di studio</b> su misura, sulle materie dell'esame di idoneità o della maturità.",
                    "<b>Studio online</b> con lezioni, mappe, pdf, interrogazioni simulate e tutor virtuale H24.",
                    "<b>Domanda d'esame</b> entro le scadenze, con il nostro supporto.",
                    "<b>Esame</b> presso la scuola individuata, preparato con prove di simulazione."]),
        ]),
        ("I risultati degli studenti", [
            ("table", ["Esame", "Esito degli studenti Janus"], [
                ["Esami di idoneità", "98% promossi"],
                ["Maturità presso scuole paritarie", "100% promossi"],
                ["Maturità con la Janus Academy", "100% promossi"],
                ["Maturità presso scuole statali", "70% promossi"],
            ]),
            "Più di 2.000 studenti negli ultimi anni: chi lavora, chi fa sport agonistico, chi vive all'estero, chi aveva lasciato la scuola. Oltre la metà degli iscritti prepara l'esame di idoneità, più del 42% la maturità. <small>Dati comunicati dall'Istituto Janus.</small>",
        ]),
        ("Per chi è pensato", [
            ("ul", ["Chi ha <b>perso uno o più anni</b> e vuole rimettersi in pari con i coetanei",
                    "<b>Adulti senza diploma</b> che ne hanno bisogno per il lavoro, un concorso o l'università",
                    "<b>Atleti</b> e studenti che vivono <b>all'estero</b> o lontano da una scuola",
                    "Chi lavora e non può seguire le lezioni del mattino o del serale"]),
        ]),
    ],
    facts=[("Esami", "Idoneità e maturità"), ("Indirizzi", "11 fra licei, tecnici e professionali"), ("Piattaforma", "Online 24/7"), ("Tutor", "Personale"), ("Maturità", "Lezioni live serali")],
    faq=[("Quanti anni posso recuperare in un anno?", "Dipende dall'ultimo anno superato, dall'età e dall'indirizzo: la normativa sugli esami di idoneità fissa requisiti precisi. Il tutor fa il calcolo esatto sul tuo caso al primo colloquio, gratis."),
         ("Dove si sostengono gli esami?", "Presso una scuola statale o paritaria, come candidato privatista. Ti aiutiamo a presentare la domanda nei tempi giusti."),
         ("Posso cambiare indirizzo rispetto alla scuola che ho lasciato?", "Sì, sostenendo gli esami integrativi nelle materie che non hai studiato."),
         ("Il diploma è uguale a quello di chi frequenta?", "Sì: è il diploma rilasciato dalla scuola presso cui sostieni l'esame di Stato, con lo stesso valore legale.")],
    related=[("/janus-diploma-online/", "Diploma online con Janus"), ("/janus-diploma-online/ragioneria-afm/", "Diploma di Ragioneria (AFM)"), ("/janus-diploma-online/liceo-scientifico/", "Liceo Scientifico online"), ("/lauree-triennali-online/", "Dopo il diploma: le lauree triennali")],
)

# ---------------------------------------------------------------------------
# Studiare all'estero (hub: /medicina-senza-test-ingresso/)
# ---------------------------------------------------------------------------
ESTERO_HUB = ("/medicina-senza-test-ingresso/", "Medicina senza test")
NOTA_ESTERO = "Rette e durate sono quelle comunicate per l'anno accademico 2026/27 dal nostro partner Study with Athena e possono variare per ateneo e per anno: fanno fede le condizioni dell'università scelta e il contratto sottoscritto. Il riconoscimento in Italia dei titoli esteri segue le procedure del Ministero competente e degli ordini professionali."

ESTERO = [
    dict(url="/odontoiatria-senza-test-ingresso/", name="Odontoiatria senza test",
         title="Odontoiatria senza test d'ingresso in Europa | UNICESD Olympo",
         desc="Studiare Odontoiatria senza test d'ingresso in Macedonia, Spagna e Romania: 5-6 anni, in inglese, tirocinio in Italia e agevolazioni per odontotecnici.",
         h1="Odontoiatria <span class=\"grad\">senza test d'ingresso</span>",
         eyebrow="Studiare all'estero · Area sanitaria",
         lead="Diventare dentista senza fermarsi davanti al numero chiuso: tre Paesi europei, corsi in inglese, tirocinio anche in Italia e un percorso seguito dalla scelta dell'ateneo al rientro.",
         facts=[("Paesi", "Macedonia, Spagna, Romania"), ("Durata", "5–6 anni"), ("Lingua", "Inglese"), ("Ammissione", "Senza test o programmata"), ("Agevolazioni", "Odontotecnici e ASO")],
         blocks=[
             ("Perché studiare odontoiatria all'estero", [
                 "In Italia Odontoiatria e protesi dentaria è a numero chiuso nazionale, con pochi posti e molti candidati. Diversi atenei europei ammettono invece senza test o con una selezione programmata e rilasciano un titolo che, per la professione di odontoiatra, rientra nel sistema europeo di riconoscimento delle qualifiche professionali.",
                 "Non è una scorciatoia: gli anni di studio, gli esami e il tirocinio sono quelli di qualsiasi corso di odontoiatria. Cambiano il modo di accedere e la lingua delle lezioni.",
             ]),
             ("Le opzioni, Paese per Paese", [
                 ("table", ["Paese", "Durata", "Accesso", "Lingua", "Note"], [
                     ["Macedonia", "5 anni", "Senza test, frequenza programmata", "Inglese", "Tirocinio in Italia, agevolazioni per odontotecnici"],
                     ["Spagna", "5 anni", "Senza test", "Inglese", "Università private tra le migliori del Paese"],
                     ["Romania", "6 anni", "Secondo l'ateneo", "Inglese", "Rette nelle private da 8.000 a 11.000 €/anno"],
                 ]),
             ]),
             ("Per chi è particolarmente adatto", [
                 ("ul", ["<b>Odontotecnici</b> diplomati, che hanno agevolazioni in alcuni atenei", "<b>Assistenti di studio odontoiatrico (ASO)</b> che vogliono fare il salto di professione", "Diplomati che non hanno superato il test italiano e non vogliono perdere anni", "Chi vuole studiare in inglese e costruirsi un profilo internazionale"]),
             ]),
             ("Come ti seguiamo", [
                 ("ol", ["Colloquio di orientamento e scelta di Paese, ateneo e lingua", "Documenti: apostille, traduzioni e dichiarazione di valore", "Domanda di ammissione entro le scadenze (di norma entro giugno)", "Trasferimento, alloggio e assistenza durante gli anni di corso", "Riconoscimento del titolo e iscrizione all'albo in Italia"]),
                 "Tutti i dettagli su documenti, alloggio e costi di agenzia sono nella pagina <a href=\"/medicina-senza-test-ingresso/\">Medicina e area sanitaria senza test</a>.",
             ]),
         ],
         faq=[("Il titolo di odontoiatra preso in Spagna o Romania vale in Italia?", "Per i titoli rilasciati in Paesi dell'Unione europea la professione di odontoiatra rientra nel riconoscimento automatico previsto dalla direttiva europea sulle qualifiche professionali; la domanda si presenta al Ministero della Salute. Per i Paesi extra UE, come la Macedonia del Nord, si segue la procedura di riconoscimento prevista per i titoli extracomunitari."),
              ("Devo sapere bene l'inglese?", "Serve un livello che ti permetta di seguire le lezioni: in fase di orientamento valutiamo il tuo livello e, se serve, ti indichiamo come rafforzarlo prima della partenza."),
              ("Posso fare il tirocinio in Italia?", "In alcuni percorsi, come quello in Macedonia, sì: è uno dei punti a favore.")],
         related=[("/medicina-senza-test-ingresso/", "Medicina e area sanitaria senza test"), ("/igiene-dentale-online/", "Igiene dentale online"), ("/studiare-medicina-in-spagna/", "Studiare medicina in Spagna"), ("/guide/riconoscimento-laurea-medicina-estero/", "Guida: riconoscimento del titolo")]),
    dict(url="/infermieristica-senza-test-ingresso/", name="Infermieristica senza test",
         title="Infermieristica senza test: Spagna e Romania | UNICESD",
         desc="Laurea in Infermieristica senza test in Spagna e Romania: 240 CFU, rette da 5.700 €/anno, formula per lavoratori con tirocinio in Italia e crediti per OSS.",
         h1="Infermieristica <span class=\"grad\">senza test d'ingresso</span>",
         eyebrow="Studiare all'estero · Area sanitaria",
         lead="La laurea in infermieristica in Spagna o in Romania, anche con una formula pensata per chi lavora già come OSS: tirocinio in Italia e pochi viaggi brevi.",
         facts=[("Paesi", "Spagna, Romania"), ("Durata", "3–4 anni"), ("Crediti", "240 CFU (4 anni)"), ("Rette", "da 5.700 €/anno"), ("Per OSS", "Riconoscimento di alcuni esami")],
         blocks=[
             ("Due strade per diventare infermiere", [
                 "La formula classica dura <b>4 anni, 240 CFU</b>, con trasferimento nel Paese: in <b>Spagna</b> (lezioni in inglese, spagnolo o francese) la retta è di <b>7.000 €/anno</b>, in <b>Romania</b> (in inglese) di <b>6.500 €/anno</b>, rateizzabili.",
                 "Per chi lavora esiste una formula in <b>3 anni in Romania</b> a <b>5.700 €/anno</b>: il tirocinio si fa in Italia, presso strutture convenzionate, per due mesi l'anno, e servono solo due o tre viaggi brevi in Romania per la parte teorica e burocratica. A chi proviene dal corso OSS vengono riconosciuti alcuni esami.",
             ]),
             ("Confronto rapido", [
                 ("table", ["Formula", "Durata", "Lingua", "Retta annua", "Frequenza"], [
                     ["Spagna", "4 anni", "Inglese, spagnolo o francese", "7.000 €", "Sul posto"],
                     ["Romania", "4 anni", "Inglese", "6.500 €", "Sul posto"],
                     ["Romania · lavoratori", "3 anni", "Inglese", "5.700 €", "Tirocinio in Italia, 2–3 viaggi"],
                 ]),
             ]),
             ("Perché la formula lavoratori interessa agli OSS", [
                 ("ul", ["Non devi lasciare il lavoro: il tirocinio è in Italia, due mesi l'anno", "L'esperienza come OSS vale il riconoscimento di alcuni esami", "La retta è la più bassa tra le opzioni disponibili", "La domanda di infermieri in Italia e in Europa resta altissima"]),
             ]),
             ("Documenti e tempi", [
                 "Serve il diploma di scuola superiore con apostille e dichiarazione di valore, le pagelle con apostille e i documenti personali. Le iscrizioni si chiudono di norma entro giugno. L'elenco completo e i costi di agenzia sono nella pagina <a href=\"/medicina-senza-test-ingresso/\">Medicina e area sanitaria senza test</a>.",
             ]),
         ],
         faq=[("La laurea in infermieristica presa in Romania vale in Italia?", "La professione di infermiere responsabile dell'assistenza generale rientra nel riconoscimento automatico dei titoli tra Paesi UE: si presenta domanda al Ministero della Salute e poi ci si iscrive all'ordine delle professioni infermieristiche."),
              ("Lavoro come OSS: quanti esami mi riconoscono?", "Dipende dal tuo attestato e dall'ateneo: te lo diciamo dopo aver visto la documentazione."),
              ("Non ho il diploma: posso iscrivermi?", "No, serve il diploma. Se non ce l'hai puoi prenderlo online con il <a href=\"/janus-diploma-online/socio-sanitario/\">diploma socio sanitario</a>.")],
         related=[("/medicina-senza-test-ingresso/", "Medicina e area sanitaria senza test"), ("/fisioterapia-senza-test-ingresso/", "Fisioterapia senza test"), ("/janus-diploma-online/socio-sanitario/", "Diploma socio sanitario online"), ("/guide/riconoscimento-laurea-medicina-estero/", "Guida: riconoscimento del titolo")]),
    dict(url="/fisioterapia-senza-test-ingresso/", name="Fisioterapia senza test",
         title="Fisioterapia senza test d'ingresso in Europa | UNICESD",
         desc="Fisioterapia senza test d'ingresso a Valencia, Craiova o Lugano (in italiano): da 6.500 €/anno, compatibile con il lavoro, 2° anno per chi ha Scienze Motorie.",
         h1="Fisioterapia <span class=\"grad\">senza test d'ingresso</span>",
         eyebrow="Studiare all'estero · Area sanitaria",
         lead="Tre percorsi per diventare fisioterapista, anche lavorando: Valencia con lezioni nel weekend, Craiova con frequenza concordabile, Lugano interamente in italiano.",
         facts=[("Paesi", "Spagna, Romania, Svizzera"), ("Durata", "3–4 anni"), ("Rette", "da 6.500 €/anno"), ("Compatibile", "Con il lavoro"), ("Da Scienze Motorie", "Ingresso al 2° anno (Valencia)")],
         blocks=[
             ("Le tre opzioni", [
                 ("table", ["Sede", "Durata", "Retta annua", "Formula"], [
                     ["Spagna · Università Europea di Madrid, sede di Valencia", "4 anni", "9.980 €", "Lezioni venerdì pomeriggio e sabato; teoria online HyFlex, pratica in presenza anche in Italia"],
                     ["Romania · Università di Medicina e Farmacia di Craiova", "3 anni", "6.500 €", "Frequenza concordabile con il lavoro"],
                     ["Svizzera · Campus Ludes, Lugano", "4 anni", "13.000 €", "Interamente in italiano, titolo dell'Università Semmelweis"],
                 ]),
             ]),
             ("Valencia: la formula per chi viene da Scienze Motorie", [
                 "Nel percorso spagnolo la teoria si segue online in modalità HyFlex e la pratica si svolge in presenza, anche in Italia, con tirocini clinici in ospedali italiani o spagnoli e simulazioni in realtà virtuale. Chi ha una laurea in <a href=\"/corsi-di-laurea/scienze-motorie/\">Scienze motorie</a> può iscriversi direttamente al <b>secondo anno</b>.",
             ]),
             ("Lugano: fisioterapia in italiano", [
                 "Per chi non se la sente di studiare in un'altra lingua c'è il Campus Ludes di Lugano: quattro anni, due semestri all'anno, lezioni interamente in italiano e titolo rilasciato dall'Università Semmelweis.",
             ]),
             ("Riconoscimento in Italia", [
                 "La fisioterapia non rientra tra le professioni a riconoscimento automatico: il titolo estero si riconosce con la procedura del Ministero della Salute, che valuta il percorso e può chiedere misure compensative. Ti affianchiamo in tutta la pratica.",
             ]),
         ],
         faq=[("Posso fare fisioterapia lavorando?", "Sì, sia a Valencia (lezioni il venerdì pomeriggio e il sabato) sia a Craiova (frequenza concordabile) il percorso è pensato anche per chi lavora."),
              ("Ho la laurea in Scienze Motorie: cosa mi conviene?", "Il percorso di Valencia, che permette l'iscrizione direttamente al secondo anno."),
              ("Quale opzione costa meno?", "Craiova, a 6.500 € l'anno per tre anni. A queste cifre vanno aggiunti viaggi, alloggio e costi di agenzia.")],
         related=[("/medicina-senza-test-ingresso/", "Medicina e area sanitaria senza test"), ("/infermieristica-senza-test-ingresso/", "Infermieristica senza test"), ("/corsi-di-laurea/scienze-motorie/", "Laurea in Scienze Motorie"), ("/corsi-di-laurea/magistrale-scienze-motorie/", "Magistrale in Scienze Motorie LM-67")]),
    dict(url="/igiene-dentale-online/", name="Igiene dentale online",
         title="Corso di Igiene Dentale online con titolo spagnolo | UNICESD Olympo",
         desc="Igiene dentale online con l'Università Europea di Madrid: 2 anni, 2000 ore, titolo del Ministero della Salute spagnolo, certificazione RX. Agevolazioni per ASO.",
         h1="Igiene dentale <span class=\"grad\">online</span>",
         eyebrow="Studiare all'estero · Area sanitaria",
         lead="Due anni, completamente online, con l'Università Europea di Madrid: il percorso per diventare igienista dentale, con agevolazioni per odontotecnici e assistenti alla poltrona.",
         facts=[("Ente", "Università Europea di Madrid"), ("Durata", "2 anni · 2000 ore"), ("Modalità", "100% online"), ("Titolo", "Ministero della Salute spagnolo"), ("Extra", "Certificazione RX")],
         blocks=[
             ("Il percorso", [
                 "È un corso di formazione professionale dell'<b>Università Europea di Madrid</b>: <b>2 anni, 2000 ore</b>, completamente online, senza costi aggiuntivi, con un tutor per tutto il percorso e un corso opzionale di spagnolo incluso. Il tirocinio è facoltativo e si può svolgere in strutture italiane.",
                 "Al termine si ottiene il <b>titolo ufficiale rilasciato dal Ministero della Salute spagnolo</b>, con la possibilità di conseguire la <b>certificazione RX</b> per le ortopantomografie.",
             ]),
             ("Per chi è pensato", [
                 ("ul", ["<b>Assistenti di studio odontoiatrico (ASO)</b> che vogliono crescere professionalmente", "<b>Odontotecnici</b> diplomati, con agevolazioni dedicate", "Chi lavora e non può trasferirsi all'estero", "Chi vuole entrare nel settore odontoiatrico con un percorso breve"]),
             ]),
             ("Validità in Italia", [
                 "Il titolo è rilasciato dal Ministero della Salute spagnolo. Per esercitare in Italia come igienista dentale va seguita la procedura di riconoscimento del Ministero della Salute italiano e l'iscrizione all'albo professionale: ti seguiamo in ogni passaggio.",
             ]),
         ],
         faq=[("Si studia davvero tutto online?", "Sì, il percorso è interamente online; solo il tirocinio, facoltativo, si svolge in presenza in strutture italiane."),
              ("Serve sapere lo spagnolo?", "Un corso di spagnolo opzionale è incluso; il tutor ti segue in italiano."),
              ("Sono ASO: ho agevolazioni?", "Sì, sono previste agevolazioni per assistenti alla poltrona e per diplomati odontotecnici.")],
         related=[("/odontoiatria-senza-test-ingresso/", "Odontoiatria senza test"), ("/medicina-senza-test-ingresso/", "Medicina e area sanitaria senza test"), ("/guide/riconoscimento-laurea-medicina-estero/", "Guida: riconoscimento del titolo")]),
    dict(url="/studiare-medicina-in-romania/", name="Medicina in Romania",
         title="Studiare Medicina in Romania: Bucarest e Craiova | UNICESD Olympo",
         desc="Medicina in Romania in inglese: Craiova senza test a 8.500 €/anno, Bucarest con test a settembre a 11.000 €/anno. Documenti, alloggio da 200 € e rientro in Italia.",
         h1="Studiare Medicina <span class=\"grad\">in Romania</span>",
         eyebrow="Studiare all'estero · Medicina",
         lead="Sei anni in inglese, rette tra le più basse d'Europa e una comunità di studenti italiani ormai numerosa: tutto quello che serve sapere per studiare medicina a Bucarest o Craiova.",
         facts=[("Durata", "6 anni"), ("Lingua", "Inglese"), ("Craiova", "Senza test · 8.500 €/anno"), ("Bucarest", "Test a settembre · 11.000 €/anno"), ("Alloggio", "200–350 €/mese")],
         blocks=[
             ("Le due università", [
                 ("table", ["Ateneo", "Ammissione", "Lingua", "Retta annua"], [
                     ["Craiova · università statale", "Senza test", "Inglese", "8.500 €"],
                     ["Bucarest · Università Titu Maiorescu", "Test a settembre, in presenza", "Inglese", "11.000 € in tre rate"],
                 ]),
                 "La Romania è uno dei Paesi più scelti dagli italiani per medicina: è nell'Unione europea, i corsi in inglese sono consolidati e il costo della vita è contenuto.",
             ]),
             ("Vivere in Romania da studente", [
                 ("ul", ["<b>Alloggio</b>: convitto universitario circa 200 € al mese, sistemazione privata da 250 a 350 €", "<b>Città consigliate</b>: Bucarest, Timisoara e Craiova", "<b>Documenti</b>: la Romania accetta anche il diploma quadriennale americano, canadese o di altri Stati; ai cittadini UE l'apostille è richiesta solo per la Romania", "<b>Lingua</b>: per chi si trasferisce e vuole imparare il rumeno ci sono corsi da 2.500 a 5.000 €"]),
             ]),
             ("Costi di agenzia e tempi", [
                 "Il servizio di Study with Athena per la Romania costa <b>5.000 € + IVA</b> e copre registrazione dello studente, presentazione dei documenti al Ministero rumeno e assistenza per il riconoscimento del titolo. Il rientro in Italia non ha costi aggiuntivi. Le iscrizioni si chiudono entro giugno.",
             ]),
             ("Rientrare in Italia", [
                 "Dal secondo anno, per chi lo desidera, si può chiedere il trasferimento in un ateneo italiano, nei limiti dei posti disponibili e secondo i bandi delle singole università. Al termine, la laurea in medicina conseguita in Romania rientra nel riconoscimento automatico tra Paesi UE.",
             ]),
         ],
         faq=[("Medicina in Romania è davvero senza test?", "A Craiova sì; a Bucarest (Titu Maiorescu) c'è un test di ammissione a settembre, in inglese e in presenza."),
              ("Quanto costa in tutto un anno?", "Alla retta (8.500 o 11.000 €) vanno aggiunti alloggio (200–350 € al mese), viaggi e spese personali; il costo di agenzia si paga una volta."),
              ("La laurea è valida in Italia?", "Sì, la laurea in medicina rilasciata in un Paese UE si riconosce con la procedura del Ministero della Salute prevista dalla direttiva europea sulle qualifiche professionali.")],
         related=[("/medicina-senza-test-ingresso/", "Medicina e area sanitaria senza test"), ("/studiare-medicina-in-spagna/", "Studiare medicina in Spagna"), ("/infermieristica-senza-test-ingresso/", "Infermieristica senza test"), ("/guide/riconoscimento-laurea-medicina-estero/", "Guida: riconoscimento del titolo")]),
    dict(url="/studiare-medicina-in-spagna/", name="Medicina in Spagna",
         title="Studiare Medicina in Spagna senza test | UNICESD Olympo",
         desc="Medicina in Spagna senza test d'ingresso a Madrid, Valencia, Malaga, Alicante e Gran Canaria: 6 anni, in inglese o spagnolo, rette da 15.000 a 20.000 €/anno.",
         h1="Studiare Medicina <span class=\"grad\">in Spagna</span>",
         eyebrow="Studiare all'estero · Medicina",
         lead="Cinque città, ammissione senza test, lezioni in inglese o in spagnolo: la Spagna è la scelta di chi vuole un'università privata di alto livello a due ore di volo dall'Italia.",
         facts=[("Città", "Madrid, Valencia, Malaga, Alicante, Gran Canaria"), ("Durata", "6 anni"), ("Lingua", "Inglese o spagnolo"), ("Ammissione", "Senza test"), ("Rette", "15.000–20.000 €/anno")],
         blocks=[
             ("Perché la Spagna", [
                 "Le università private spagnole che ammettono senza test offrono strutture moderne, ospedali universitari e un ambiente internazionale. La lingua (inglese o spagnolo) e la vicinanza culturale con l'Italia rendono l'inserimento più semplice.",
                 "La retta varia in base alla sede, <b>da 15.000 a 20.000 € all'anno</b>. Il servizio di agenzia per la Spagna è di <b>1.500 € all'anno</b>.",
             ]),
             ("Che cosa serve per iscriversi", [
                 ("ul", ["Diploma quinquennale con apostille dell'Aja e dichiarazione di valore", "Pagelle di tutti gli anni con apostille", "Estratto di nascita europeo, documento d'identità, codice fiscale", "Certificato di sana e robusta costituzione e fototessere"]),
                 "Le iscrizioni si chiudono di norma entro giugno: conviene iniziare la raccolta dei documenti in inverno.",
             ]),
             ("Non solo medicina", [
                 "In Spagna sono disponibili anche <a href=\"/odontoiatria-senza-test-ingresso/\">odontoiatria</a> (5 anni, in inglese), <a href=\"/infermieristica-senza-test-ingresso/\">infermieristica</a> (7.000 €/anno) e <a href=\"/fisioterapia-senza-test-ingresso/\">fisioterapia</a> a Valencia.",
             ]),
         ],
         faq=[("Serve lo spagnolo per studiare medicina in Spagna?", "No, se scegli un corso in inglese. Imparare lo spagnolo resta utile per i tirocini in ospedale."),
              ("Posso rientrare in Italia durante il corso?", "Dal secondo anno si può chiedere il trasferimento in un ateneo italiano, nei limiti dei posti disponibili."),
              ("La laurea spagnola vale in Italia?", "Sì, la laurea in medicina rilasciata in un Paese UE si riconosce con la procedura del Ministero della Salute.")],
         related=[("/medicina-senza-test-ingresso/", "Medicina e area sanitaria senza test"), ("/studiare-medicina-in-romania/", "Studiare medicina in Romania"), ("/odontoiatria-senza-test-ingresso/", "Odontoiatria senza test"), ("/guide/riconoscimento-laurea-medicina-estero/", "Guida: riconoscimento del titolo")]),
]
